#!/bin/sh -e
# purpose: like `wrrarms-w3m`, but using `pandoc` instead

wrrarms get -l \
        -e "net_url|add_prefix '# url: '" \
        -e "pretty_url|add_prefix '# pretty: '" \
        -e "pretty_nurl|add_prefix '# normalized: '" -- "$1"
echo
wrrarms run -- pandoc -f html -t org --wrap=none "$1"
