#!/usr/bin/env bash
set -e

usage() {
    cat << EOF
usage: $0 [--help] WRR_FILE

Generate a plain text preview of a WRR file containing an HTML document using \`pandoc\`.

# Options:

  --help                print this message and exit

# Example:

  $0 path/to/wrr/file/containing/html.wrr
EOF
}

while (($# > 0)); do
    case "$1" in
    --help) usage; exit 0 ;;
    *) break ;;
    esac
    shift
done

(($# > 0)) || { echo "error: need a WRR_FILE"; echo; usage; exit 1; } >&2

wrrarms get -l \
        -e "net_url|add_prefix '# url: '" \
        -e "pretty_url|add_prefix '# pretty: '" \
        -e "pretty_nurl|add_prefix '# normalized: '" -- "$1"
echo
wrrarms run -- pandoc -f html -t org --wrap=none "$1"
