/*
 * Copyright (c) 2023-2026 Jan Malakhovski <oxij@oxij.org>
 *
 * This file is a part of `hoardy-web` project.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * Global notifications generator.
 */

"use strict";

// flags
// do we have a newly- or recently failed to be stashed or saved/archived to local storage reqres?
let gotNewSyncedOrNot = false;
// do we have a newly- or recently failed to be archived reqres?
let gotNewArchivedOrNot = false;
// do we need to show empty queue notification?
let wantArchiveDoneNotify = true;
// do we have new queued reqres?
let gotNewQueued = false;
// do we have new reqres in limbo?
let gotNewLimbo = false;
// last time we notified the user about it
let gotNewLimboLastNotification = 0;
// do we have new problematic reqres?
let gotNewProblematic = false;
// do we have new buggedOut reqres?
let gotNewBuggedOut = false;

function formatFailures(why, willRetry, list) {
    let parts = [];
    let allReal = true;
    let allRecoverable = true;
    let someRecoverable = false;
    for (let [reason, unarchived] of list) {
        allReal = allReal && unarchived.real;
        let recoverable = unarchived.recoverable;
        allRecoverable = allRecoverable && recoverable;
        someRecoverable = someRecoverable || recoverable;
        parts.push(`- ${why} ${unarchived.queue.length} reqres because ${reason}.`);
    }
    if (willRetry) {
        let cont = "to retry them manually you need to press the \"Retry\" button on the \"Queued/Failed\" line in the popup.";
        if (!someRecoverable)
            parts.push("\nNone of these will be retried automatically, " + cont);
        else if (!allRecoverable)
            parts.push("\nSome of these won't be retried automatically, " + cont);
        else
            parts.push("\nAll of these will be retried automatically.");
    }
    if (!allReal) {
        parts.push("\nSome of the above failures are not real and were instead generated by `Paranoid error handling` mode. You can disable it and then press the \"Retry\" button on the \"Queued/Failed\" line in the popup to make `Hoardy-Web` retry these operations for each reqres separately.");
    }
    return parts.join("\n");
}

// make a log of no more than `problematicNotifyNumber`
// elements, merging those referencing the same URL
function formatProblematic(list) {
    let latestMap = new Map();
    for (let i = list.length - 1; i >= 0; --i) {
        let loggable = list[i][0];
        let tabcfg = getTabConfig(loggable.tabId, loggable.fromExtension);
        if (!tabcfg.problematicNotify)
            continue;

        let desc = (loggable.method ? loggable.method : "?") + " " + loggable.url;
        let l = latestMap.get(desc);
        if (l === undefined) {
            if (latestMap.size < config.problematicNotifyNumber)
                latestMap.set(desc, 1);
            else
                break;
        } else
            latestMap.set(desc, l + 1);
    }

    if (latestMap.size === 0)
        return [];

    let latestDesc = [];
    for (let [k, v] of latestMap.entries()) {
        if (k.length < 80)
            latestDesc.push(`${v}x ${k}`);
        else
            latestDesc.push(`${v}x ${k.substr(0, 80)}\u2026`);
    }
    latestDesc.reverse();
    return latestDesc;
}

function notifyAboutUn(what, list, willRetry, all, promises) {
    let prefix = `error-${what}-`;

    // clear stale
    for (let label of all) {
        if (label.startsWith(prefix)) {
            let storeID = label.substr(prefix.length);
            if (list.every((e) => e[0] !== storeID))
                promises.push(browser.notifications.clear(label));
        }
    }

    if (!config.persistFailedNotify)
        return;

    // generate new ones
    for (let [storeID, byReasonMap] of list) {
        let where;
        if (storeID === "exportAs")
            where = "Export via `saveAs`";
        else if (storeID === "localStorage")
            where = "Browser's local storage";
        else
            where = `Archiving server at ${storeID}`;

        promises.push(browser.notifications.create(prefix + storeID, {
            title: "Hoardy-Web: FAILED",
            message: escapeNotification(config, `${where}:\n${formatFailures("Failed to " + what, willRetry, byReasonMap.entries())}`),
            iconUrl: iconURL("failed", 128),
            type: "basic",
        }));
    }
}

function doGlobalNotify(all, promises) {
    let now = Date.now();

    // record the current state, because the rest of this chunk is async
    let rrUnproblematic = reqresUnproblematic;
    // continue collecting the new ones
    reqresUnproblematic = [];

    if (config.problematicNotify === true && rrUnproblematic.length > 0) {
        let latest = formatProblematic(rrUnproblematic);
        promises.push(browser.notifications.create("", {
            title: "Hoardy-Web: AUTO",
            message: escapeNotification(config, `Auto-unmarked ${rrUnproblematic.length} problematic reqres:\n` + latest.join("\n") + annoyingNotification(config, "Generate notifications about > ... 'problematic' reqres")),
            iconUrl: iconURL("idle", 128),
            type: "basic",
        }));
    }

    if (gotNewProblematic && reqresProblematic.length > 0) {
        gotNewProblematic = false;

        if (config.problematicNotify !== false) {
            // generate a new one
            let latest = formatProblematic(reqresProblematic);
            promises.push(browser.notifications.create("warning-problematic", {
                title: "Hoardy-Web: WARNING",
                message: escapeNotification(config, `Have ${reqresProblematic.length} reqres marked as problematic:\n` + latest.join("\n") + annoyingNotification(config, "Generate notifications about > ... 'problematic' reqres")),
                iconUrl: iconURL("problematic", 128),
                type: "basic",
            }));
        }
    } else if (reqresProblematic.length === 0)
        // clear stale
        promises.push(browser.notifications.clear("warning-problematic"));

    let fatLimbo = reqresLimbo.length > config.limboMaxNumber
                || reqresLimboSize > config.limboMaxSize * MEGABYTE;

    if (fatLimbo && gotNewLimbo && (now - gotNewLimboLastNotification) > config.limboNotifyInterval * 1000) {
        gotNewLimbo = false;

        if (config.limboNotify) {
            gotNewLimboLastNotification = now;

            // generate a new one
            promises.push(browser.notifications.create("warning-fatLimbo", {
                title: "Hoardy-Web: WARNING",
                message: escapeNotification(config, `Too much stuff in limbo, collect or discard some of those reqres to reduce memory consumption and improve browsing performance.` + annoyingNotification(config, "Generate notifications about > ... too much stuff in limbo")),
                iconUrl: iconURL("limbo", 128),
                type: "basic",
            }));
        }
    } else if (!fatLimbo)
        // clear stale
        promises.push(browser.notifications.clear("warning-fatLimbo"));

    if (gotNewQueued && reqresQueue.length > 0) {
        gotNewQueued = false;

        if (config.archiveStuckNotify && !config.archive && !config.stash) {
            promises.push(browser.notifications.create("warning-notSaving", {
                title: "Hoardy-Web: WARNING",
                message: escapeNotification(config, "Some reqres are waiting in the archival queue, but both reqres stashing and archiving are disabled."),
                iconUrl: iconURL("archiving", 128),
                type: "basic",
            }));
        }
    } else if (config.archive || config.stash)
        // clear stale
        promises.push(browser.notifications.clear("warning-notSaving"));

    let rrUnstashed = Array.from(reqresUnstashedIssueAcc[1].entries());

    if (gotNewSyncedOrNot) {
        gotNewSyncedOrNot = false;

        notifyAboutUn("stash", rrUnstashed, true, all, promises);
    }

    let rrUnarchived = Array.from(reqresUnarchivedIssueAcc[1].entries());

    if (gotNewArchivedOrNot) {
        gotNewArchivedOrNot = false;

        notifyAboutUn("archive", rrUnarchived, true, all, promises);

        if (wantArchiveDoneNotify && reqresQueue.length === 0 && rrUnstashed.length === 0 && rrUnarchived.length === 0) {
            wantArchiveDoneNotify = false;

            if (config.archiveDoneNotify) {
                // generate a new one
                promises.push(browser.notifications.create("ok-done", {
                    title: "Hoardy-Web: OK",
                    message: escapeNotification(config, "Archiving appears to work OK!\n\nThis message won't be repeated unless something breaks." + annoyingNotification(config, "Generate notifications about > ... newly empty archival queue")),
                    iconUrl: iconURL("idle", 128),
                    type: "basic",
                }));
            }
        }
    }

    let rrBuggedOut = Array.from(reqresBuggedOutIssueAcc[1].entries());

    if (gotNewBuggedOut && rrBuggedOut.length > 0) {
        gotNewBuggedOut = false;

        promises.push(browser.notifications.create("error-buggedOut", {
            title: "Hoardy-Web: ERROR",
            message: escapeNotification(config, `Bugged out:\n${formatFailures("Failed to process", false, rrBuggedOut)}`),
            iconUrl: iconURL("error", 128),
            type: "basic",
        }));
    } else if (rrBuggedOut.length === 0)
        // clear stale
        promises.push(browser.notifications.clear("error-buggedOut"));
}

async function runNotifier(func, ...args) {
    // get shown notifications
    let all_ = await browser.notifications.getAll();
    let all = Object.keys(all_);

    // collect into here
    let promises = [];

    func(...args, all, promises);

    // wait for all the promisse to finish
    await Promise.all(promises.map((p) => p.catch(logError)));
}

function scheduleGlobalNotifications(timeout) {
    resetSingletonTimeout(scheduledHidden, "notify", timeout, () => runNotifier(doGlobalNotify));
    // NB: needs scheduleUpdateDisplay after
}
