#+MACRO: div2 [[./popup.html#div-$1][$2]]
#+MACRO: stat2 [[./popup.html#div-stats.$1][$2]]
#+MACRO: config2 [[./popup.html#div-config.$1][$2]]
#+MACRO: tabconfig2 [[./popup.html#div-tabconfig.$1][$2]]
#+MACRO: button2 [[./popup.html#$1][$2]]
#+MACRO: stat ([[./popup.html#div-stats.$1][glob]])
#+MACRO: stats ([[./popup.html#div-stats.$1][glob]], [[./popup.html#div-tabstats.$1][cur]])
#+MACRO: perSource ([[./popup.html#div-config.$1][glob]], [[./popup.html#div-tabconfig.$1][cur]], [[./popup.html#div-tabconfig.children.$1][chld]], [[./popup.html#div-config.root.$1][root]], [[./popup.html#div-config.background.$1][bg]], [[./popup.html#div-config.extension.$1][ext]])
#+MACRO: logPage ([[./popup.html#showState][glob]], [[./popup.html#showTabState][cur]])
#+MACRO: unmarkProblematic ([[./popup.html#unmarkAllProblematic][glob]], [[./popup.html#unmarkAllTabProblematic][cur]])
#+MACRO: reportit [[https://github.com/Own-Data-Privateer/hoardy-web/issues][open an issue on GitHub]] or [[https://oxij.org/#contact][get in touch otherwise]]
#+OPTIONS: H:5

#+BEGIN_EXPORT html
<div class="less">
#+END_EXPORT
* How to read this document
:PROPERTIES:
:CUSTOM_ID: top
:UNNUMBERED: notoc
:END:

If you are reading this on GitHub, it's recommended you switch to the [[https://oxij.org/software/hoardy-web/tree/master/extension/page/help.org][version hosted on the author's web site]] instead.
This pages is written in =org-mode= markup language and it uses a lot of its advanced features, which GitHub does not implement, so this page is almost unreadable on GitHub.

Moreover, if you already have =Hoardy-Web= extension installed, then, instead of reading this document on GitHub or from author's web site, it is highly recommended you refer to this document by clicking the "Help" button in the extension's own popup UI.
Doing that will make this document interactive: the settings popup will be displayed on the right on this page and hovering over or clicking references to configuration options on this page will highlight them in the settings popup.
It will also have a nicely formatted "Table of Contents" section there.
See [[../../doc/gallery.md][screenshots]] if you want to get an idea of how it will look.

#+BEGIN_EXPORT html
</div>
#+END_EXPORT

#+TOC: headlines 5
* Introduction
The =Hoardy-Web= software project has many parts, all of which are documented separately.
*This page documents the =Hoardy-Web= web browser extension (add-on) and nothing else.*
For links to documentation for other parts of this project, see the [[#more][bottom of this page]].

In this document, unless specified otherwise, "=Hoardy-Web=" refers to the =Hoardy-Web= extension, not the other parts of the =Hoardy-Web= software project.

The main purpose of =Hoardy-Web= is to help you **passively**, in background, capture and archive =HTTP= requests and responses your web browser does as you browse the web.
However, =Hoardy-Web= does a bit more than that, also implementing a bunch of features that you'll probably find useful in related workflows.

In =Hoardy-Web= you can check the description of each status line, button, and/or configuration option by hovering over it or by pressing the nearby =?= button.
However, many of those descriptions might make little sense without you first learning the general operation principles of =Hoardy-Web= and some of its quirks.
This document is designed to explain that.
Most notably, this document

- describes [[#start][what the extension does under the hood]] to capture, archive, and replay your web traffic;
- all the while explaining its most important configuration options, invokable actions, their effects, and available integrations with related tools;
- discusses some [[#additional][additional features]] of =Hoardy-Web=,
- lists all of =Hoardy-Web='s [[#shortcuts][keyboard shortcuts]] and [[#context-menu][context menu actions]];
- talks through some [[#workflows][common workflows]] =Hoardy-Web= can support;
- explains all [[#errors][error messages and codes]] the extension can produce;
- lists all known [[#bugs][extension's own issues and relevant web browser bugs]];
- answers various [[#faq][frequently asked questions]].
* Conventions
:PROPERTIES:
:CUSTOM_ID: conventions
:END:

When you open this document by clicking the =Help= button in extension's UI, this page has two parts: this help text, and an =iframe= with a completely unrolled popup UI in it.

The whole page will switch between single- and two-column layouts depending on available viewport width (which depends on device width and zoom level).
In single-column layout the popup UI is placed after the end of the help text.
In two-column layout they are placed side-by-side.

In both layouts:

- [[#faq][links that look like this]] are references to other parts of this page;
  clicking these links will scroll this page to the place they point to and then highlight the relevant part;

- {{{config2(colors,links that look like this)}}} are references to elements of the popup UI,

  - in single-column layout, clicking such a link will scroll the whole page to the corresponding element in the popup UI =iframe= and then highlight it;

  - in two-column layout, clicking or hovering over such a link will scroll only the popup UI =iframe= around to put the corresponding referenced element into view and then highlight it;

  - the highlighted element will stop being highlighted if you click anywhere else on the page;

- [[./changelog.html][links that look like this]] are references to other internal pages of =Hoardy-web=;
  clicking them will navigate this tab there;

- finally, [[https://oxij.org/software/][links like this]] are references to external URLs.

In cases when clicking on a link scrolls this page around or navigates to another page, pressing the "Back" button of your browser will get you back to the exact link you clicked and then highlight it, making it easy to get back to reading from the exact place you left off.

**Go forth and try it by clicking one or more of the above links.**

The above rules are also apply on all other internal pages of =Hoardy-Web=, e.g. the [[./changelog.html][=Changelog= page]].
* General operation
:PROPERTIES:
:CUSTOM_ID: start
:END:
** Glossary
- A /reqres/ (/REQuest/ + /RESponse/) is an internal object containing captured information about an =HTTP= request and its response, including their headers and data, and some meta-information (whether it originates from an extension, =tabId= it originates from, its state, etc).

  =Hoardy-Web= captures, dumps, archives, and manipulates reqres by first rendering them into [[../../doc/data-on-disk.md][=WRR= ("Web Response+Request") file format]].

  The page referenced by the above link has a longer data-format glossary, comparison of =WRR= to other related file formats, and the complete formal definition of =WRR=, if you are interested.
** State Diagram
Reqres change their internal states according to the following state diagram (which is explained below):

#+BEGIN_SRC
(start) -> (request sent) -> (nIO) -> (headers received) -> (nIO) --> (body received)
   |                           |                              |             |
   |                           v                              v             v
   |                     (no_response)                   (incomplete)   (complete)
   |                           |                              |             |
   |                           \                              |             |
   |\---> (canceled) ----\      \                             |             |
   |                      \      \                            \             |
   |\-> (incomplete_fc) ---\      \                            \            v
   |                        >------>---------------------------->-----> (finished)
   |\--> (complete_fc) ----/                                             /  |
   |                      /                                             /   |
   \----> (snapshot) ----/       /- (collected) <--------- (picked) <--/    |
                                /       ^                      |            |
 (stashToLS?) <----------------/        |                      v            v
      |                                 \- (in_limbo) <- (stashToLS?) <- (dropped)
      v                                           |                         |
  (queued) <---- (unarchived) <- (stashToLS?)     |                         |
      |                               ^           \-----> (discarded) <-----/
   /-\|          /---> {U} -----------/                        ^
   ^  |          |      \                                      |
   |  |          |       \--> (forgotten) ((-> (saved)))       |
   |  |          |                                             |
 {RE} |          v                  {{!saving && !submitting}} |
      |\----> (saveAs) -> (exported) -------------------------/|
      |                       /                                |
      | {U} <-\    /---------/                                 |
      |        v   v                        {{!saving}}        |
      |\----> (srvIO) -> (submitted) -------------------------/|
      |                     /                                  |
      |                    /              {{delete}}           |
      | {U} <-\     /-----/     /-----------------------------/|
      |        \   /           /                               |
      |        v   v          /       {{re-archive}}           |
      |\---> (saveToLS) -> (saved) -------------------> {RE}   |
      |                                                        |
      \--------------------------------------------------------/
#+END_SRC
** Step 1: Tracking
:PROPERTIES:
:CUSTOM_ID: tracking
:END:

=Hoardy-Web= attaches to your browser's runtime and tracks progress of =HTTP= requests and their responses, capturing both their request and response headers and data at appropriate times in the browser's request and response processing pipeline.

Whether =Hoardy-Web= will track a given request depends on the =Track new requests= toggles in the settings popup:

- {{{tabconfig2(collecting,this one (cur))}}} controls whether =Hoardy-Web= will track new requests originating from the currently active tab;

- {{{tabconfig2(children.collecting,this one (chld))}}} controls whether it will track new requests originating from new tabs spawned from the currently active tab (aka "children tabs", e.g., via middle mouse click, context menu, etc);

- then, {{{config2(root.collecting,this one (root))}}} controls whether it will track new requests originating from new tabs opened via browser's "New Tab" browser action (i.e. the plus sign in the tab bar, =Control+T=, menu item, etc),

- meanwhile, {{{config2(background.collecting,this one (bg))}}} controls whether =Hoardy-Web= will track new background requests, which are requests without an associated tab;

- while {{{config2(extension.collecting,this one (ext))}}} controls tracking of requests generated by extensions, which are background requests generated by installed browser add-ons.

Press =?= symbols to see tooltips explaining what each of them does.

Disabling any of these toggles does not stop tracking of already initiated requests, it only stops new requests controlled by that toggle from being tracked.
*** The networking states of the State Diagram
As shown on the above diagram, a new reqres, i.e., a new =HTTP= request and response pair, proceeds through the following networking states:

- =start=: the starting state;

- =request sent=, (response) =headers received=, (response) =body recived=: these are the normal stages of =HTTP= request and response tracking via [[https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest][=webRequest= sub-API of =WebExtensions= API]];

- =nIO=: normal network IO performed by the browser in between =HTTP= request stages;

- =canceled=: the request was canceled before it was sent because
  - you canceled it manually using the browser's =Stop= button;
  - an ad-blocking extension like =uBlock Origin=, global work offline mode of Firefox-based browsers, or this extension's own per-tab/per-source [[#work-offline][work offline mode]] blocked it;
  - the browser canceled it by itself, e.g. when redirecting an =http://= URL to an =https://= URL in =HTTPS=-only mode;
  - etc;

  =unsent= would have probably been a better name for this, but all browsers call it =canceled= internally, so =Hoardy-Web= follows that convention;

- =no_response=: the request was sent, but no response was received because
  - you pressed the =Stop= button before it got a response;
  - a connection to the target server was rejected;
  - the server decided to ignore the request completely;
  - network timeout was reached;
  - etc;

- =incomplete=: the request was sent, its response headers were received, but then the loading was interrupted before all of the response body was received;

- =incomplete_fc=: only on Firefox-based browsers: the browser loaded the response data of this reqres directly from its cache, but did not give it to =Hoardy-Web=;

  this is just how Firefox handles things sometimes;
  usually, this only happens for images;

  this is a separate state, because usually this means this URL was successfully archived before;
  if it was not, reload the page with =Control+F5=;

- =complete=: the reqres was completed successfully;

- =complete_fc=: the reqres was completed successfully from browser's cache;

- =snapshot=: this reqres was produced by taking a =DOM= (Document Object Model) snapshot, i.e., by capturing a raw =HTML= or =XML= of the current state of the tab/frame, not by capturing a network request;

  this can be done using {{{button2(snapshotAll,this)}}} or {{{button2(snapshotTab,that)}}} buttons, or similar [[#shortcuts][keyboard shortcuts]];

- =finished=: the terminal state of this step, no new events for this reqres will come from the browser.
*** Glossary
- An /in-flight reqres/ {{{stats(in_flight)}}} is a reqres that did not reach the =finished= state yet, in the logs {{{logPage}}} such reqres will be shown to be in =in_flight= state.

  These stats are represented as sums of sizes of three sets of reqres:

  - "bona fide in-flight reqres": reqres that are still being heavily tracked via =webRequest= and/or =debugger= APIs;

    meaning, they are yet to reach the =headers received= state in =webRequest=-handling code and =body recived= state in =debugger=-handling code;

  - "finishing up reqres": reqres that have captured all the metadata they can and are now waiting to be =finished=;

    meaning, they reached the =headers received= state but not the =body recieved= state in =webRequest=-handling code and/or are waiting to be matched up with their =webRequest= counter-parts in =debugger=-handling code;

  - "almost done reqres": the number of reqres that =finished= being tracked but hadn't yet been [[#classification][classified]] and dumped to =WRR=.

  On Firefox, nothing should ever get stuck, if something seems to be stuck in =in_flight= state, it's probably still loading (or it is a bug in this extension or the browser, both which do happen, rarely).

  On Chromium, [[#chromium-bug-stuck][limitations of the Chromium's debugging interface mean a request can get stuck among the reqres represented by the first two numbers above]].
  If the first number is zero, however, then the second and third numbers should also rapidly become zero, at most after {{{config2(workaroundChromiumDebugTimeout,two times this many seconds)}}}.

  If some reqres got stuck in one of the =in_flight= states, you can forcefully move them out of that state using {{{button2(stopAllInFlight,this)}}}, {{{button2(stopAllTabInFlight,that)}}}, or similar buttons in the logs {{{logPage}}}.

- A /finished reqres/ is a reqres that reached the =finished= state.

- A /final networking state/ is the last state a reqres had before it =finished=: i.e. =complete=, =incomplete=, =canceled=, etc.
** Overview of the following archiving-related steps
:PROPERTIES:
:CUSTOM_ID: overview
:END:

In principle, when a reqres reaches its =finished= state, the primary objective of =Hoardy-Web= with respect to that reqres is complete, so that reqres could be dumped to disk and forgotten about.

Unfortunately for =Hoardy-Web=, browsers do not allow web apps and extensions to simply write files to user's file system, and all existing browser APIs that do allow for persistence to disk in some way all have different limitations.
Also, it is quite useful to have more states after =finished= to improve the UI and allow for various conditional workflows.

Which is why =Hoardy-Web= has quite a lot of states after the =finished= state in the above diagram.
To give a simple overview of most of the following steps, generally speaking, after =Hoardy-Web= produces a =finished= reqres, it proceeds as follows:

- It applies various classification rules to the reqres in question to decide whether that reqres should end up in =collected=, =discarded=, or =in_limbo= state.
- It puts =in_limbo= reqres away until you manually indicate what you want it to do with it or some other event moves it out from =in_limbo= state automatically.
- It creates a new log record for =collected= and =discarded= reqres so that you could later inspect that record even if the reqres in question got deleted from memory.
- Then, it queues =collected= reqres for archival while simply deleting =discarded= reqres from memory.
- Then, it starts processing that queue in background to actually archive said reqres using one or more supported archiving methods.
** Step 2: Classification
:PROPERTIES:
:CUSTOM_ID: classification
:END:

When a reqres reaches the =finished= state it gets classified by the computations described below.
*** Partial, buggy, and incomplete reqres
:PROPERTIES:
:CUSTOM_ID: partial
:END:

Sometimes networking issues and/or browser bugs prevent complete collection of (parts of) reqres data or metadata.
To provide indication of this, =Hoardy-Web= keeps track of such things and marks such reqres with flags that indicate that the reqres in question has

- a =partial request body=, which is denoted by =partial= flag in the logs {{{logPage}}};

  see the relevant browser bugs of [[#firefox-bug-no-post][Firefox]] and [[#chromium-bug-no-post][Chromium]];

- =buggy request metadata= or =buggy response metadata=, which is denoted by =buggy= flag in the logs {{{logPage}}};

  see the relevant browser bugs of [[#firefox-bug-race][Firefox]] and [[#chromium-bug-no-wre][Chromium]];

- an =incomplete response body=, denoted by =incomplete= flag in the logs {{{logPage}}};

  this flag actually gets set in the [[#tracking][tracking stage]], so its presence also forces the reqres in question to stop in =incomplete= or =incomplete_fc= final networking state discussed above;

  usually, this condition is caused by networking issues like a connection getting interrupted before the whole body was fetched, but it can be caused by browser bugs, like [[#chromium-bug-autodetach][Chromium occasionally detaching its debugger at random]].
*** Problematic reqres
A reqres can also be classified as =problematic=.
This feature [[#problematic][shall be discussed in a much later section]] since the =problematic= flag is completely orthogonal to the current archiving-related discussion.
*** Picked and Dropped reqres
Each new =finished= reqres advances either to the =picked= or the =dropped= state.
Which of those two states gets selected is decided based on reqres' [[#tracking][final networking state]], its [[#partial][partial, buggy, and incomplete flags]] discussed above, and the {{{div2(pick-options,=Pick reqres for archival when they finish= options)}}}:

- By default, all =complete= and =complete_fc= reqres get =picked=, regardless of their =HTTP= response status codes or any other errors reported by the browser.

  After all, it appears that the data of those reqres was properly fetched, so they should be archived.

- Similarly, {{{config2(archivePartialRequest,reqres with =partial request body= flag set)}}} and {{{config2(archiveBuggy,reqres with one of the =buggy * metadata= flags set)}}} are also =picked= by default.

  It is recommended you keep those toggles enabled as relevant flags are usually caused by browser bugs and are thus unfixable unless you run =Hoardy-Web= on a customly patched browser.
  Also, these issues usually don't prevent replay of captured reqres.
  Thus, in these cases, archiving some data is usually better than archiving none.

- In contrast, picking of {{{config2(archiveCanceled,reqres in =canceled= state)}}}, {{{config2(archiveNoResponse,reqres in =no_response= state)}}}, and {{{config2(archiveIncompleteResponse,reqres with =incomplete response body= flag set)}}} is disabled by default because response-incomplete reqres are usually useless and can be easily fixed by reloading a page in question.
*** Glossary
- A /problematic reqres/ {{{stats(problematic)}}} is a /finished reqres/ that satisfies the conditions set by {{{div2(problematic-options,=Mark reqres as 'problematic' when they finish= settings)}}}, as [[#problematic][shall be discussed later]].

- A /picked reqres/ {{{stats(picked)}}} is a /finished reqres/ that satisfied the conditions controlled by {{{div2(pick-options,=Pick reqres for archival when they finish= settings)}}} on entering the =finished= state.

- A /dropped reqres/ {{{stats(dropped)}}} is a /finished reqres/ that did *not* satisfy the conditions controlled by {{{div2(pick-options,=Pick reqres for archival when they finish= settings)}}} on entering the =finished= state.
** Step 3: Collection, Discarding, Logging, and Limbo
:PROPERTIES:
:CUSTOM_ID: main
:END:

On exit from the =finished= state and the classification performed there, each reqres gets split into

- a =loggable=, which is a hollow =reqres= structure without any request or response data, and
- a =dump=, which is a [[../../doc/data-on-disk.md][=WRR=-formatted dump]] of the original =reqres= structure.

(Since those tuples can be reconstructed back into the original =reqres=, the following will continue to refer to them as if nothing has changed when the fact they are now being internally represented by those tuples is not relevant.)

On entering =collected= or =discarded= state, =loggable= metadata of each reqres is copied into the recent reqres log {{{logPage}}} and is kept there until the size of the log reaches {{{config2(history,this many elements)}}}, at which point the older elements of the log start being elided automatically.

You can also ask =Hoardy-Web= to forget all history manually by pressing {{{button2(forgetAllLog,this button)}}}, or to forget history of reqres generated by the currently active tab by pressing {{{button2(forgetAllTabLog,that button)}}} instead, or do the same by using similar buttons in the logs {{{logPage}}}.
Using the latter allows for more granular control via the reqres filtering options available there.

However, note that [[#problematic][currently =problematic= reqres]] will not get automatically elided from the log, nor forgotten by using the above buttons, see there for more info.
*** Normal mode
:PROPERTIES:
:CUSTOM_ID: no-limbo
:END:

In other words, normally:
- =picked= reqres proceed to the =collected= state, get logged, and then get =queued= for archival;
- =dropped= reqres proceed to being logged and =discarded= then from memory.
*** Limbo mode
:PROPERTIES:
:CUSTOM_ID: limbo
:END:

However, sometimes you might want to actually look at a web page before deciding if you want to archive it or not.
The naive way to do it would be to load a page with {{{tabconfig2(collecting,capture)}}} disabled first, look at it, and then, if you want to save it, enable {{{tabconfig2(collecting,it)}}}, and reload the page again with browser's cache disabled via =Control+F5= (and it has to be =Control+F5=, not just =F5=, because otherwise some URLs, on Firefox, might produce reqres in =incomplete_fc= state, and on Chromium, their re-fetching could be silently skipped).

Obviously, this is both annoying and will force you to fetch everything twice.

Which is why =Hoardy-Web= implements /limbo mode/.
With one of the limbo mode options enabled, =Hoardy-Web= will instead capture everything as normal, but then, instead of sending the newly captured reqres to =collected= or =discarded= states immediately, it will put them into =in_limbo= state where they would linger until you /collect/ or /discard/ them manually by pressing the appropriate buttons on the corresponding stats lines {{{stats(in_limbo)}}} or until {{{div2(closed-tab-options,=Closed tabs= options)}}} make a decision semi-automatically for you.

A =picked= reqres will be put into =in_limbo= when its corresponding {{{perSource(limbo,=Pick into limbo= setting)}}} is enabled.

Similarly, a =dropped= reqres will be put into =in_limbo= when its corresponding {{{perSource(negLimbo,=Drop into limbo= setting)}}} is enabled.
(These options mainly exists for debugging.)

If {{{config2(limboNotify,this option)}}} is enabled and there are more than {{{config2(limboMaxNumber,this number)}}} reqres =in_limbo= or the total size of all dumps =in_limbo= is more than {{{config2(limboMaxSize,this size)}}} (in MiB), =Hoardy-Web= will complain to remind you to collect or discard some of them.
*** Glossary
- A /collected reqres/ {{{stats(collected)}}} is a reqres that was (either automatically or manually) sent to the =collected= state.

- A /discarded reqres/ {{{stats(discarded)}}} is a reqres that was (either automatically or manually) sent to the =discarded= state.

- An /in-limbo reqres/ {{{stats(in_limbo)}}} is a reqres that is being held =in_limbo= until you manually /collect/ or /discard/ it.

- A /queued reqres/ ({{{stat2(queued,displayed)}}} on the {{{stat2(queued_failed,Queued/Failed)}}} line) is a =collected= reqres that is still =queued= for archival.
** (Optional) Step 3.5: Stashing
:PROPERTIES:
:CUSTOM_ID: stashing
:END:

In most cases you would probably want to prevent loss of successfully captured but yet unarchived reqres when
- you quit or restart your browser by accident,
- your computer unexpectedly looses power,
- =Hoardy-Web= crashes or gets reloaded/updated unexpectedly
before you =collected= or =discarded= everything from =in_limbo= or =Hoardy-Web= has successfully archived everything from its archiving queue.

This is why =Hoardy-Web= implements the optional =stashToLS?= states on the above diagram and a special =stashed= reqres status.
The =stashed= status is, essentially, a flag that says this reqres was temporarily backed up into browser's local storage.
This process can be controlled using the following options:

- When {{{config2(archive,=Archive 'collected' reqres= option)}}} is disabled but {{{config2(stash,=Stash 'collected' reqres into local storage= option)}}} is enabled, instead of archiving newly =queued= reqres, =Hoardy-Web= will /stash/ their =(loggable, dump)= tuples into browser's local storage.

- Similarly, when both {{{config2(stash,=Stash 'collected' reqres into local storage= option)}}} and one of the relevant per-source {{{perSource(stashLimbo)}}} settings is enabled, then all newly generated =in_limbo= reqres from that source will also get immediately stashed into browser's local storage.

Moreover, the following section will discuss how =Hoardy-Web= will try stashing =unarchived= reqres into browser's local storage too.

Note however, that even with {{{config2(stash,stashing)}}} enabled =Hoardy-Web= will skip disk IO whenever possible: e.g., if both {{{config2(archive,=Archive 'collected' reqres=)}}} and {{{config2(archiveSubmitHTTP,=Submit dumps via 'HTTP'=)}}} options discussed below are enabled, =Hoardy-Web= will first try to archive each new =collected= reqres straight from memory to the archiving server and only if that process fails will it attempt stashing them to local storage instead.

Meaning that

- stashing of non-=in_limbo= reqres is usually completely free and so you should probably keep {{{config2(stash,that option)}}} always enabled;
- stashing of =in_limbo= reqres via one of the {{{perSource(stashLimbo)}}} options is not free, so if you almost never archive from limbo then keeping those options enabled will waste disk IO, so you might want to disable at least some of them in that case.

The above also implies that, technically, stashing is not a silver bullet against data loss.
To try and make it such would mean unconditional immediate stashing of all captured data, which would waste a lot of disk IO on most =Hoardy-Web= configurations.

When both {{{config2(stash,=Stash 'collected' reqres into local storage= option)}}} and {{{config2(archive,=Archive 'collected' reqres= option)}}} are disabled, then, after a new reqres gets =queued=, =Hoardy-Web= will generate a new notification complaining about it, unless {{{config2(archiveStuckNotify,that option)}}} is disabled too.

You can also forcefully stash all currently =queued=, =in_limbo=, and =unarchived= reqres by pressing {{{button2(stashAll,this button)}}}.
It stashes everything immediately and unconditionally, ignoring all other stashing settings.
When reloading the extension via the {{{div2(reloadSelf,=Reload= button)}}} or via {{{config2(autoReloadOnUpdates,=Auto-reload on updates= option)}}}, this action will be run automatically.

If {{{config2(persistFailedNotify,this option)}}} is enabled and some reqres fail to stash, a new notification will be generated.
*** Glossary
- A /stuck queued reqres/ is a =queued= reqres that got stuck in the archival queue, e.g., because it got queued while {{{config2(archive,=Archive 'collected' reqres= option)}}} was disabled.

- A /stashed reqres/ {{{stat(stashed)}}} is a reqres that was temporarily =stashed= (backed-up) into browser's local storage while it is still being kept in =Hoardy-Web='s memory.
  I.e., the stash is a persistent on-disk backup for in-memory reqres.

- A /failed to stash reqres/ {{{stat(unstashed)}}} is a reqres that is currently =unstashed=, i.e., a reqres that failed to be stashed into browser's local storage.
  Note that reqres for which stashing was not even attempted are not included in this set.
  It is also a part of the sum of the "Failed" part of the {{{stat2(queued_failed,Queued/Failed)}}} line.

  You can retry stashing these by pressing {{{button2(retryAllUnstashed,this button)}}}.
** Step 4: Archival
:PROPERTIES:
:CUSTOM_ID: archival
:END:

When {{{config2(archive,=Archive 'collected' reqres= toggle)}}} is enabled, =Hoardy-Web= will pop =queued= reqres from the archival queue one by one and then perform one or more of the following (in order they are listed):

- if {{{config2(archiveExportAs,=Export dumps via 'saveAs'= option)}}} is enabled but {{{config2(exportAsBundle,bundling)}}} is disabled, =Hoardy-Web= will simply
  - compress the =dump=, {{{config2(gzipExportAs,if enabled)}}}, and
  - export the resulting [[../../doc/data-on-disk.md][=WRR file=]] via browser's =saveAs= mechanism (i.e., generate a fake-Download);

- if both {{{config2(archiveExportAs,=Export dumps via 'saveAs'= option)}}} and {{{config2(exportAsBundle,bundling)}}} are enabled, =Hoardy-Web= will
  - append the =dump=, as a byte string, to a (per-=bucket=, see below) [[../../doc/data-on-disk.md][=WRR bundle=]],
  - and then, if the =WRR bundle= gets larger than {{{config2(exportAsMaxSize,this)}}} or after a delay controlled by {{{config2(exportAsInFlightTimeout,that)}}} and {{{config2(exportAsTimeout,this)}}} options,
    - compress the result, {{{config2(gzipExportAs,if enabled)}}}, and
    - export the resulting =WRR bundle= via browser's =saveAs= mechanism (i.e., generate a fake-Download);

- if {{{config2(archiveSubmitHTTP,=Submit dumps via 'HTTP'= option)}}} is enabled, =Hoardy-Web= will submit the =dump= to the archiving server at {{{config2(submitHTTPURLBase,=Server URL= setting)}}} by making an =HTTP POST= request with the =dump= as request body (which is denoted by =srvIO= state on the diagram above);

- if any of the above fails =Hoardy-Web= will

  - move the reqres into the =unarchived= state,

  - if {{{config2(stash,=Stash 'collected' reqres into local storage= option)}}} is enabled, it will try stashing the =(loggable, dump)= tuple into browser's local storage (which is denoted by =stashToLS?= states on the diagram above) and record but ignore any errors produced while doing that, and

  - stop processing this reqres;

- if {{{config2(archiveSaveLS,=Save reqres into local storage= option)}}} is enabled, =Hoardy-Web= will

  - try saving the =(loggable, dump)= tuple into browser's local storage (which is denoted by =saveToLS= state on the diagram above),

  - if saving fails, move the reqres into the =unarchived= state instead,

  - if saving succeeds, discard the reqres from memory,

  - stop processing this reqres;

- if {{{config2(archiveSaveLS,=Save reqres into local storage= option)}}} is disabled, =Hoardy-Web= will simply discard the reqres from memory, as if saving succeeded.

In the cases of stashing and archiving to local storage, the =dump='s get compressed if {{{config2(gzipLSDumps,this option)}}} is enabled.

You can enable more than one {{{div2(archive-methods,archival method)}}} at the same time.
For a given =loggable=, =Hoardy-Web= will remember and skip previously successful archival methods if the =loggable= ever returns to the archival pipeline.
This can happen when one of the archival methods fails and =Hoardy-Web= auto-retries it, or you later ask =Hoardy-Web= to retry the archival manually with {{{button2(retryAllUnarchived,this)}}} or {{{button2(retryAllFailed,that)}}} buttons, or if you [[#re-archival][re-archive]] it again.

Note the difference between /stashed/ and /saved/ reqres:

- /stashed/ reqres are kept in memory until they get successfully archived by all configured {{{div2(archive-methods,archival methods)}}} (or until you manually discard them, in case they were stashed =in_limbo=);
- /saved/ reqres get dumped into browser's local storage and, if that succeeds, discarded from memory (until you manually load them back from {{{button2(showSaved,there)}}}).
*** Buckets (aka collections)
:PROPERTIES:
:CUSTOM_ID: bucket
:END:

Sometimes you might want to semi-automatically split your collected archives into separate disjoint sets.
Say, for instance, you want to split out archives generated by a select tab into a separate set you plan to share with somebody else.
In =Hoardy-Web= such sets are called /buckets/.
=WARC=-based tools sometimes call these "collections" instead.

To implement this, for each reqres in the archival queue, =Hoardy-Web= takes a =bucket= value from the most specific applicable "Bucket" setting {{{perSource(bucket)}}}.

Evaluation of =bucket= is done just before each archival attempt, so if the queue is not yet empty, and you disable {{{config2(archive,=Archive 'collected' reqres=)}}}, edit some of the "Bucket" settings, and enable {{{config2(archive,it)}}} again, =Hoardy-Web= will start using the new setting immediately.

When exporting via =saveAs=, =bucket= value will be used in the file name of the generated fake-Download =WRR bundle= file (=.wrrb=) and the dumps will be split into separate fake-Download files by said =bucket=.
I.e., internally, the =WRR bundle= discussed above is actually a set of per-=bucket= =WRR bundle='s.

When submitting to an =HTTP= server, =Hoardy-Web= will specify =bucket= as a query parameter (named "profile", for historical reasons) to each =HTTP POST= request, which will cause the {{{config2(submitHTTPURLBase,configured archiving server)}}} to put those =WRR= files into a directory with the same name.

When stashing or saving to local storage, =Hoardy-Web= will record the value of =bucket= into each =loggable= before saving data to disk.
If you restart your browser, thus starting a new =Hoardy-Web= session, =Hoardy-Web= will use the old stashed/saved =bucket= values for all new attempted archivals of old reqres generated by previous sessions.

So, for example, if you want to share a subset of your captures, you can

- set {{{tabconfig2(bucket,this option)}}} in a tab to, say, "share",
- clear your browser's cache,
- then and only then navigate to a web page archives of which you plan to share,
- thus separating out those reqres into separate =saveAs= =WRR bundle='s with "share" in their name and/or putting them into a separate archiving server directory named "share", depending on {{{div2(archive-methods,archival methods)}}}.
*** Handling of failures
As noted above, if any of the {{{div2(archive-methods,archival methods)}}} fail, the reqres in question will be moved into the =unarchived= state.

Submissions of reqres that are =unarchived= because of networking issues will be retried automatically every 60 seconds.
Archivals of reqres rejected by the archiving server or those that failed to be saved to browser's local storage will not be retried automatically as those usually happen when there is no space left on the device you are archiving to.

You can retry all archiving failures by pressing one of {{{button2(retryAllUnarchived,this)}}} or {{{button2(retryAllFailed,that)}}} buttons.
You can also use them to nudge the archiving sub-process awake if something archival-related appears to be stuck.

If {{{config2(persistFailedNotify,this option)}}} is enabled and a new reqres recently moved to the =unarchived= state, a new notification will be generated.
If {{{config2(archiveDoneNotify,this option)}}} is enabled, a new notification will be generated when the archival queue gets empty the very first time or after any failures.
*** Glossary
- A /failed to archive reqres/ {{{stat(unarchived)}}} is a reqres that is currently in =unarchived= state, i.e., a reqres that failed to be archived by one of the enabled {{{div2(archive-methods,archival methods)}}}.
  It is also a part of the sum of the "Failed" part of the {{{stat2(queued_failed,Queued/Failed)}}} line.

  You can retry archiving these by pressing {{{button2(retryAllUnarchived,this button)}}}.

- An /exported reqres/ {{{stat(exportedAs)}}} is a reqres that was successfully =exported= by generating a fake-Download containing its =dump=.

- A /submitted reqres/ {{{stat(submittedHTTP)}}} is a reqres that was successfully =submitted= to the archiving server and thus was discarded from memory.

- A /saved reqres/ {{{stat(saved)}}} is a reqres that was successfully =saved= by being archived into browser's local storage.

- /An archived reqres/ is either /exported/, /submitted/, or /saved/ reqres.
** (Optional) Step 4.5: Re-archival
:PROPERTIES:
:CUSTOM_ID: re-archival
:END:

=Hoardy-Web= allows reqres =saved= in browser's local storage to be re-archived the second (third, fourth, etc) time.
This feature uses the same archiving pipeline as above with three major differences:

- Unlike archival, re-archival is not automatic.

  You will have to manually press its {{{div2(rearchive-actions,popup UI action buttons)}}}, a similar button on the {{{button2(showSaved,=Saved in Local Storage= page)}}}, or [[#shortcuts][keyboard shortcuts]].

- Re-archival pipeline uses a separate data structure for recording reqres that end up in the =unarchived= state.
  The =unarchived= reqres of re-archival pipeline do not get retried, becoming =forgotten= instead.

  After all, they are already archived in browser's local storage, thus, if they fail to re-archive, =Hoardy-Web= can simply forget about them until they get re-loaded from local storage again.

- For performance and safety reasons (to prevent possible race conditions between archival and re-archival), re-archival pipeline currently blocks the main thread of =Hoardy-Web= completely, until all re-archival actions finish.

  The capture machinery and some UI updates will continue to work, but stashing, archival, and post-archival computations will not happen while re-archival is running.

Re-archival can be most useful in following use cases:

- You want to collect and accumulate lots of reqres before re-archiving them by the means of {{{config2(rearchiveExportAs,=Export via 'saveAs'=)}}} to make the UI less annoying and to {{{config2(gzipExportAs,compress)}}} the resulting =WRR bundle='s better.

- You run =Hoardy-Web= under a Fenix-based mobile browser, where {{{config2(archiveExportAs,Export via =saveAs=)}}} does not work, you are unable to run an {{{config2(submitHTTPURLBase,archiving server)}}} on the same device, because it's an unrooted mobile phone, and you don't want to submit your dumps over the Internet, because you are feeling paranoid.

  By using this feature, you can delay re-archival to your archiving server until you [[#fenix][get back to your home Wi-Fi network, and re-archive everything all at once there]].

- You run =Hoardy-Web= under Tor Browser and you [[#tor-browser][want your browsing/capture and archival/replay completely isolated from each other]].
*** Controlling what gets re-archived
The simplest way to re-archive old data is to configure the desired {{{div2(rearchive-methods,re-archival methods)}}} and then press {{{button2(rearchiveAllSaved,this button)}}}.
This will simply re-archive everything stored in local storage unconditionally.

Since archival and re-archival use the same archiving pipeline, similarly to =unarchived= reqres, re-archival also remembers if a given reqres was previously (re-)archived using the given archival method.
Thus, enabling a {{{div2(rearchive-methods,re-archival method)}}} and then pressing {{{button2(rearchiveAdjunctSaved,this button)}}} will skip re-archival of reqres that were previously archived or re-archived using that same method.

I.e., you can just configure the desired {{{div2(rearchive-methods,re-archival methods)}}} and then press {{{button2(rearchiveAdjunctSaved,that button)}}} from time to time, with each new press re-archiving a new batch.

If you want more control over what gets re-archived, you can also

- open the {{{button2(showSaved,=Saved in Local Storage= page)}}},
- make a subset of =saved= reqres using the filtering options there, and then
- re-archive only those, by pressing the =Re-archive= button there.
*** Deletion of successfully (re-)archived reqres
In use cases
- where, for safety, you archive both externally and into local storage at the same time, or
- where, because of your [[#tor-browser][browser setup]], your archive into local storage and then periodically export your saved data via re-archival
you can easily delete your previously successfully archived or re-archived reqres from your local storage by
- pressing one {{{div2(rearchive-actions,re-archival action buttons)}}} while {{{div2(rearchive.andDelete,deletion)}}} is set,
- using a similar button and option on {{{button2(showSaved,=Saved in Local Storage= page)}}}, or
- pressing the {{{button2(deleteRearchived,=Delete old= button)}}}.

However, the first two options should be used with caution:

- The behaviour of the {{{button2(rearchiveAdjunctSaved,=Re-archive new= button)}}} with {{{div2(rearchive.andDelete,deletion)}}} enabled can be surprising if you sometimes use both available {{{div2(rearchive-methods,re-archival methods)}}} and sometimes only one of them.

  For example, if you had both re-archival methods enabled and some reqres failed to be archived with one of them, but then, later, you disable that method and run {{{button2(rearchiveAdjunctSaved,=Re-archive new=)}}} with {{{div2(rearchive.andDelete,deletion)}}} enabled again, those previously failed to re-archive reqres will be deleted too.

  In other words, unlike with normal archival, re-archival failures don't get recorded anywhere.

- Re-archiving by the means of {{{div2(rearchive-actions,re-archival action buttons)}}} (or their {{{button2(showSaved,=Saved in Local Storage= page)}}} equivalent) when both {{{config2(rearchiveExportAs,=Export via 'saveAs'=)}}} and {{{div2(rearchive.andDelete,deletion)}}} (or its {{{button2(showSaved,=Saved in Local Storage= page)}}} equivalent) are enabled is [[#unsafe-saveas][unsafe because of browser API limitations]].

  The essence of the issue there is that if a new reqres gets captured and then saved into local storage via the normal {{{config2(archive,=Archive 'collected' reqres=)}}} machinery right at the moment you press the {{{button2(rearchiveAdjunctSaved,=Re-archive new= button)}}} and the generated =WRR bundle= then [[#unsafe-saveas][silently fails to be saved to disk via =saveAs=]], then that sneaky reqres will still get deleted, and, thus, permanently lost.

  Thus, if you want to do this safely, you should:

  - {{{div2(rearchive-actions,re-archive)}}} with {{{div2(rearchive.andDelete,deletion)}}} disabled;
  - confirm that all generated fake-Downloads were actually successfully saved to disk;
  - then immediately press the {{{button2(deleteRearchived,=Delete old= button)}}} without touching any {{{div2(rearchive-methods,re-archival method toggles)}}}.

  Alternatively, you can also do this:

  - disable {{{config2(archive,=Archive 'collected' reqres= option)}}};
  - {{{div2(rearchive-actions,re-archive)}}} with {{{div2(rearchive.andDelete,deletion)}}} disabled;
  - confirm that all generated fake-Downloads were actually successfully saved to disk;
  - enable {{{div2(rearchive.andDelete,deletion)}}} without changing any other options;
  - press {{{button2(rearchiveAdjunctSaved,=Re-archive new= button)}}},
  - re-enable {{{config2(archive,archival)}}}.

  The last button press should then produce an =Re-archived and deleted <N> reqres invoking 0 archiving actions and <N> deletions from local storage.= notification.
  I.e. it will just delete all of them, without actually performing any archivals.

  Or, alternatively, as a last step, you can open {{{button2(showSaved,=Saved in Local Storage= page)}}}, set =Exported via 'saveAs'= filter to =true= and then press =Delete= button there.

In short, {{{div2(rearchive-actions,re-archival actions)}}} with {{{div2(rearchive.andDelete,deletion)}}} set should be used with lots of care.
This is why the {{{div2(rearchive.andRewrite,rewrite)}}} and {{{div2(rearchive.andDelete,deletion)}}} options and their equivalents on {{{button2(showSaved,=Saved in Local Storage= page)}}} are ephemeral and will be reset the next time you reopen the popup or that page.

Additionally, note that you can press {{{div2(rearchive-actions,re-archive)}}} and {{{button2(deleteRearchived,deletion)}}} buttons one after the other immediately, their actions will get queued for execution properly and won't interfere with each other.
Thus, if you are re-archiving via {{{config2(rearchiveSubmitHTTP,submission via =HTTP=)}}} it's safe to mash them one after the other, you don't need to sit there and wait for one action to finish before pressing the other button, since submission over =HTTP= reports errors properly.

However, note that re-archival by {{{config2(rearchiveSubmitHTTP,submission via =HTTP=)}}} with {{{div2(rearchive.andDelete,deletion)}}} enabled is safe to use too.
On-the-fly deletion is much more efficient compared to re-archival step followed by a {{{button2(deleteRearchived,separate deletion step)}}} because updated reqres' archival flags need not be written back into local storage.
Thus, since {{{config2(rearchiveSubmitHTTP,submission via =HTTP=)}}} does report its errors properly, successfully re-archived reqres can be immediately and safely deleted from local storage in that case, which would save you a lot of time and disk writes if you are re-archiving a lot of stuff all at once.
** (Optional) Step 5: Replay
:PROPERTIES:
:CUSTOM_ID: replay
:END:

When your {{{config2(submitHTTPURLBase,archiving server)}}} supports it and {{{config2(replaySubmitHTTP,this option)}}} is not disabled, =Hoardy-Web= enables its integration with replay over =HTTP=.

Pressing

- {{{button2(replayAll,this button)}}} re-navigates each open tab for which {{{tabconfig2(replayable,this setting)}}} is enabled to its replay page;

- {{{button2(replayTabBack,this buttons)}}} re-navigates the currently active tab regardless of any settings.

Alternatively, =Hoardy-Web= implements /auto-replay mode/, in which all navigations are automatically redirected to their replays URLs instead:

- {{{tabconfig2(autoReplay,this toggle (cur))}}} enables auto-replay mode in the currently active tab;

- {{{tabconfig2(children.autoReplay,this toggle (chld))}}} enables it for children tabs spawned from the currently active tab, thus making all link middle-clicks open replay pages;

- there is also a {{{config2(root.autoReplay,toggle (root))}}} for controlling the default value of the above three options in newly opened windows.

If the archiving server does not support replay or when {{{config2(replaySubmitHTTP,this option)}}} is disabled, auto-replay mode will cancel those requests and generate error notifications instead.

Currently auto-replay mode only works for top-level navigation requests and performs redirects regardless of your {{{config2(submitHTTPURLBase,archiving server)}}} having an archive of the URL in question.
(This will be improved in the future.)
* Additional features
:PROPERTIES:
:CUSTOM_ID: additional
:END:
** Problematic reqres
:PROPERTIES:
:CUSTOM_ID: problematic
:END:

Conventional web browsers provide no explicit indication when a part of a web page fails to load properly.
Apparently, you are expected to actually look at the page with your eyes, notice something looking broken, and reload it manually if so.

Obviously, this can be quite inconvenient when you want to be sure that the whole page with all of its resources was archived.
Especially when parts of a dynamically loaded page might simply silently fail to be rendered by associated =JavaScript= because some of the =HTTP= requests that =JavaScript= did in background failed, or, on a static web page, layout and =CSS= might have made some of the incompletely loaded parts of the page invisible (by design or by accident).

So, to provide an explicit indicator for such situations, =Hoardy-Web= keeps track of reqres that fail to load properly and, in the [[#classification][classification step]], marks them with a =problematic= flag which influences

- toolbar button's icon, badge, and title;

  all of which depend on the numbers of currently =problematic= reqres;

- the corresponding stat lines {{{stats(problematic)}}} in the popup;

- the logs {{{logPage}}}, which shows =problematic= reqres in a separate section;

  *additionally, note that =problematic= reqres can't be dropped from the logs until their =problematic= flags are unset;*

  the ways in which this can be done (automatically or manually) shall be discussed below;

- and nothing else.

*In other words, the =problematic= flag is a UI indicator, it does not influence archival in any way.*

What gets marked as =problematic= is controlled by {{{div2(problematic-options,=Mark reqres as 'problematic' when they finish= options)}}}.
By default, =HTTP= requests that failed to get a response, those that were fetched with [[#partial][buggy metadata or have incomplete response bodies]], and those for which the browser reported /potentially problematic errors/ but then =Hoardy-Web= =picked= them anyway, will be marked as =problematic=.

/Potentially problematic errors/ are errors like

- "this request failed because of a networking issue",
- "this request was aborted because the =JavaScript= function making it decided to cancel it when you moved your mouse cursor away from a video thumbnail it was needed for",
- and similar things that probably imply some part of the page was left unfetched,

but *not* errors like

- "fetching of this request was aborted because the server redirected it to a URL blocked by =uBlock Origin=",
- "the browser decided against rendering of this data",
- "the browser failed to render this data because this image file is broken",
- and similar errors where the request was canceled on purpose or the data was properly fetched.

In principle, =Hoardy-Web= could have been designed to never record the errors of the latter category in the first place, thus simplifying the above bit, but =Hoardy-Web= is designed to follow the philosophy of "collect everything as browser gives it, as raw as possible".
The raw error strings reported by the browser for each reqres can be seen in the logs {{{logPage}}}.

When {{{config2(problematicNotify,that option)}}} is not disabled, new notifications will be produced each time a new =problematic= reqres appears.
*** Automatic unmarking of =problematic= reqres
:PROPERTIES:
:CUSTOM_ID: unproblematic
:END:

In some situations some of the =problematic= flags on some of your reqres might become irrelevant as you fetch more data.

For example, say, you load a tab, some of its images fail to load completely and get marked as =problematic=, so you re-load that tab again, and then all reqres that failed to be fetched the first time get fetched properly the second time.
Do you still care that some of those old reqres failed to fetch properly the first time?
Probably not.

But to be absolutely pedantic in such a situation, you would actually need to carefully check that all of your old =problematic= reqres actually got re-fetched properly, just in case the browser decided to skip fetching of some of them, which could happen with modern =HTML= lazy-loading features, and only then stop caring about them.
Obviously, actually doing this manually each time would be incredibly annoying.

Which is why =Hoardy-Web= provides a {{{div2(unproblematic-options,bunch of configuration options)}}} that automatically unmark old =problematic= reqres in various situations.
By default, those options are set in a way that produces least annoying and least surprising workflows, but you might want to tweak them if you need that process to be stricter.

In particular, note that the default value of {{{config2(autoUnmarkProblematicSimilarAcrossLimbo,Auto-unmark =problematic= reqres ... regardless of its =in_limbo= state)}}} option produces slightly imprecise results when combined with picking into limbo {{{perSource(limbo)}}}.
Thus, if you are feeling pedantic, you might want to disable that option.
Though, if you do that, the resulting behaviour of =Hoardy-Web= will probably feel rather counter-intuitive, at least at first.

When {{{config2(problematicNotify,that option)}}} is set to its right-most state, new notifications will be produced each time an old =problematic= reqres gets automatically unmarked.
*** Manual handling of =problematic= reqres
:PROPERTIES:
:CUSTOM_ID: manual-problematic
:END:

In most use cases, =Hoardy-Web= is entirely capable of automatically maintaining a relevant set of still =problematic= reqres, helping you figure out what still needs to be fetched to completely archive a given web page properly.
However, in some situations, you might also want to manually unmark some of your =problematic= reqres.
To do that you can:
- unmark all currently =problematic= reqres globally or in a select tab via popup buttons {{{unmarkProblematic}}} and/or [[#shortcuts][keyboard shortcuts]];
- unmark =problematic= reqres by using similar buttons in the logs {{{logPage}}}, which allows for more granular control via the reqres filtering options available there.
*** I don't care about any of this and notifications about =problematic= reqres annoy me!
:PROPERTIES:
:CUSTOM_ID: suppress-problematic
:END:

If you don't care about the =problematic= flag in a select tab and those notifications annoy you, you should disable {{{tabconfig2(problematicNotify,this per-source option)}}}.
If such notification annoy you in general, you can disable the {{{config2(problematicNotify,global option)}}} instead.

Note, however, that you probably shouldn't be disabling too many  {{{div2(problematic-options,=Mark reqres as 'problematic' when they finish= options)}}}.
This way, even with notifications disabled, you would still be able see a correct number of =problematic= reqres in extension's toolbar button's badge, popup {{{stats(problematic)}}}, and the logs {{{logPage}}}.
** Work offline mode
:PROPERTIES:
:CUSTOM_ID: work-offline
:END:

Sometimes, you might want to block a select tab from performing new =HTTP= requests.

Normally, when you use the [[../../tool/][=hoardy-web= tool]] to replay old page visits, =HTTP= replay pages generated by its =serve= sub-command and static website mirrors generated by its =mirror= sub-command remap all URLs of page requisites to point to local replay URLs and files.
(Though, it is configurable.)

Unfortunately, =HTML5= specification is quite large, complex, and it gets updated all the time.
Additionally, =hoardy-web= can have bugs in its remapping code.
Moreover, interactions between remapped pages and some browser extensions can sometimes break things too.
In other words, some of those replayed pages could end up referencing Internet resources when they should not.

In a similar vein, imagine a situation where, while looking at your logs {{{logPage}}}, you discover that a web page originating from a certain domain is making an awful lot of tracking =HTTP= requests:
- say, for instance, you notice that a certain web page is generating tracking =HTTP= requests from its =JavaScript= event handlers, like when you switch to/from its tab, when you drag your mouse cursor around that page, and/or when you select text on that page;
- or, maybe, you have =JavaScript= disabled on that page, but as you scroll it around you notice that it starts generating suspicious =HTTP= requests because that page uses lazily loaded single-pixel =HTML img= tags to track you scrolling it anyway;
- or, maybe, you have both =JavaScript= and lazy loading disabled, but then you notice that the font size on that page is deliberately too small, so you have to tweak that tab's zoom level, which changes that tab's viewport size, which then makes your browser generate new tracking =HTTP= requests because that page uses its responsive =CSS= to track that;
- or, maybe, you notice other ways =HTML= standards are being exploited to archive similar results.

Now, say that, after considering the above, you discover that you dislike the idea of "TVs that watch you back" from Orwell's "1984" greatly, and you would rather ensure that

- your browser won't ever try to access the Internet when you open one of the =hoardy-web serve='ed or =hoardy-web mirror='ed pages; and
- your browser won't ever notify a page's origin server when you start interacting with it long after you loaded it and then forgot about it for a while.

In some cases you might even feel paranoid enough to want to prevent your browser from opening non-remapped jump-links (=a href=) on replay pages, even when you explicitly click them (by accident).

Desktop versions of Firefox-based browsers have a =File > Work Offline= option that can solve most of this, but it disables all new requests browser-wise, which is quite inconvenient and error-prone if you want to keep some of your tabs offline while not restricting others, and it will break replay over =HTTP= with =hoardy-web serve=.
Chromium-based browsers do not appear to have such a feature at all.

To solve this issue, =Hoardy-Web= implements its own granular /work offline mode/ which can be controlled via per-tab/per-source =Work offline= toggles {{{perSource(workOffline)}}}.

Unlike the =File > Work Offline= option of Firefox, enabling any of these toggles:

- does not break =hoardy-web serve= replay URLs;
- does not break any requests that are already in flight;
- does not prevent generation/capture of new =canceled= reqres when both of the corresponding =Track new requests= toggles {{{perSource(collecting)}}} and {{{perSource(collectingWorkOffline)}}} are set;

  this makes it possible to inspect the resulting =canceled= reqres in the logs {{{logPage}}};

  though, note that those newly generated =canceled= reqres will be marked as =problematic= if {{{config2(markProblematicDroppedWithErrors,that option)}}} is enabled.

Finally, there is also a {{{div2(special-tab-options,bunch of options)}}} that automatically enable work offline mode in tabs with various classes of URLs.
By default, work offline mode is enabled for =file:= and replay URLs to stop any pages generated by =hoardy-web mirror= and =hoardy-web serve= to accessing the Internet.
* Keyboard shortcuts
:PROPERTIES:
:CUSTOM_ID: shortcuts
:END:

- On Firefox-based browsers, you can see and edit all keyboard shortcuts via =Add-ons and themes= (=about:addons=) -> the gear icon -> =Manage Extension Shortcuts=.
- On Chromium-based browsers, you can see and edit all keyboard shortcuts via the menu -> =Extensions= -> =Manage Extensions= (=chrome://extensions/=) -> =Keyboard shortcuts= (on the left).

On this browser, =Hoardy-Web= implement the following keyboard shortcuts:

#+BEGIN_EXPORT html
<table id="tbl-sk">
  <thead>
    <tr>
      <th>Description</th>
      <th>Currently</th>
      <th>Default</th>
    </tr>
  </thead>
  <tbody id="tbody-sk">
  </tbody>
</table>
#+END_EXPORT

* Context menu actions
:PROPERTIES:
:CUSTOM_ID: context-menu
:END:

Moreover, =Hoardy-Web= provides context menu actions to:

- open a replay of a link in a new tab or window;

- open a link in a new tab or window with currently active tab's {{{tabconfig2(children.collecting,tracking in children tabs setting)}}} negated.
  I.e.,

  - right-mouse clicking while pointing at a link and
  - selecting =Hoardy-Web > Open Link in New Tracked/Untracked Tab= menu item,

  is equivalent to

  - toggling {{{tabconfig2(children.collecting,this)}}},
  - middle-mouse clicking a link,
  - toggling {{{tabconfig2(children.collecting,this)}}} again.
* Workflows
:PROPERTIES:
:CUSTOM_ID: workflows
:END:
** Using =Hoardy-Web= with Fenix (Firefox on Android)
:PROPERTIES:
:CUSTOM_ID: fenix
:END:

Since {{{config2(archiveExportAs,=Export dumps via 'saveAs'= option)}}} and {{{config2(rearchiveExportAs,its re-archival variant)}}} do not work under Firefox on Android, you will have to use {{{config2(archiveSubmitHTTP,=Submit dumps via 'HTTP'=)}}} and/or {{{config2(rearchiveSubmitHTTP,its re-archival variant)}}} to extract your archives from =Hoardy-Web=.
There are several ways you can do this:

- You can simply
  - run your archiving server with =--host 0.0.0.0= argument on your PC to allow non-localhost connections;
  - put your PC and your Android device on the same Wi-Fi network;
  - setup your =Hoardy-Web= to archive data via {{{config2(archiveSubmitHTTP,=Submit dumps via 'HTTP'=)}}};
  - point {{{config2(submitHTTPURLBase,=Server URL= setting)}}} to your PC;
  - and then just let =Hoardy-Web= work normally.

- Alternatively, you can
  - tether your Android device to your PC via a USB cable;
  - setup and enable USB Debugging there;
  - run
    =sudo adb kill-server && sudo adb start-server && adb reverse tcp:3210 tcp:3210=
    on your PC, which would setup a reverse port forwarding from your Android device to your PC;
  - setup your =Hoardy-Web= to archive data via {{{config2(archiveSubmitHTTP,=Submit dumps via 'HTTP'=)}}};
  - use the default value of {{{config2(submitHTTPURLBase,=Server URL= setting)}}};
  - and then just let =Hoardy-Web= work normally.

- Finally, to archive data when using your Android device while it's untethered from your PC:
  - setup your =Hoardy-Web= to archive data via {{{config2(archiveSaveLS,=Save reqres into local storage=)}}}, which is the default;
  - enable {{{config2(rearchiveSubmitHTTP,re-archival via =HTTP=)}}};
  - configure your PC and your {{{config2(submitHTTPURLBase,=Server URL= setting)}}} using one of the above ways;
  - and then, after getting back to your PC and connecting your Android device to it via Wi-Fi or USB (with the above =adb= commands included), [[#re-archival][re-archive]] your archived data incrementally.
** Using =Hoardy-Web= with Tor Browser
:PROPERTIES:
:CUSTOM_ID: tor-browser
:END:

When running =Hoardy-Web= under Tor Browser you'll probably want to configure it in such a way so that all of the machinery of =Hoardy-Web= is completely invisible to web pages running under your Tor Browser, to prevent fingerprinting.

Thus, you can simply use =Hoardy-Web= extension configured to {{{config2(archiveSaveLS,=Save reqres into local storage=)}}}, which is the default, and then {{{config2(rearchiveExportAs,export your dumps manually)}}} at the end of a browsing session via {{{div2(rearchive-actions,re-archival actions)}}}, which would take a couple of clicks, as [[#re-archival][discussed above]].

Or, alternatively, you can switch to using {{{config2(archiveExportAs,=Export dumps via 'saveAs'=)}}} by default instead, disabling the other archiving methods.
I expect this to work fine for 99.99% of the users 99.99% of the time, but, technically speaking, [[#unsafe-saveas][this is unsafe]].
Also, by default, browser's UI will be slightly annoying, since =Hoardy-Web= will be generating new "Downloads" all the time, but that issue [[#faq-firefox-saveas][can be fixed with a small =about:config= change]].

Using either of the above methods won't allow you to replay archived captures, though.
*** Replay
:PROPERTIES:
:CUSTOM_ID: tor-browser-replay
:END:

In theory, running [[../../tool/][=hoardy-web serve=]] listening on a loopback IP address should prevent web pages from accessing it, since the browsers disallow cross-origin requests from non-localhost domains to localhost, thus making the normal {{{config2(archiveSubmitHTTP,=Submit dumps via 'HTTP'= mode)}}} with {{{config2(replaySubmitHTTP,replay)}}} setup quite viable.
However, Tor Browser is configured to proxy everything via the TOR network by default, so you need to configure it to exclude the requests to =hoardy-web serve= from being proxied.

A slightly more paranoid than normal way to do this is as follows:

- Run the server as =hoardy-web serve --host 127.0.99.1= or similar.
- Point the {{{config2(submitHTTPURLBase,=Server URL= setting)}}} to the resulting URL (=http://127.0.99.1:3210/= or similar).
- Switch to {{{config2(archiveSubmitHTTP,=Submit dumps via 'HTTP'=)}}} by default, disabling the other archiving methods.
- Go to =about:config= in your Tor Browser and add =127.0.99.1= (or similar) to =network.proxy.no_proxies_on=.

Why?
When using Tor Browser, you probably don't want to use =127.0.0.1= and =127.0.1.1= as those are normal loopback IP addresses used by most things, and you probably don't want to allow any =JavaScript= code running in Tor Browser to (potentially, if there are any bugs) access to those.
Yes, if there are any bugs in the cross-domain check code, with this setup =JavaScript= could discover you are using =Hoardy-Web= (and then, in the worst case, access all of your archived captures and DOS your system by flooding your disk with garbage dumps), but it won't be able to touch the rest of your stuff listening on your other loopback addresses.

So, while this setup is not super-secure if your Tor Browser allows web pages to run arbitrary =JavaScript= (in which case, let's be honest, no setup is secure), with =JavaScript= always disabled, to me, it looks like a completely reasonable thing to do.
* Error messages and codes
:PROPERTIES:
:CUSTOM_ID: errors
:END:
** Error messages, as seen in generated notifications
:PROPERTIES:
:CUSTOM_ID: error-notifications
:END:

- One of
  - =`Hoardy-Web` can't establish a connection to the archiving server at `<URL>`=,
  - =The archiving server at `<URL>` appears to be unavailable=,
  - =The archiving server at `<URL>` does not allow archiving, it appears to be a replay-only instance=,
  - =... Failed to archive <N> items because this archiving server is unavailable=,
  - =... Failed to archive <N> items because this archiving server does not support archiving=,
  - =... Failed to archive <N> items because this archiving server appears to be defunct=, or
  - =... Failed to archive <N> items because `Hoardy-Web` can't establish a connection to the archiving server: <reason>=:

  Are you running the [[../../simple_server/][=hoardy-web-sas= archiving server script]] or a [[../../tool/][=hoardy-web serve=]] instance?

  In the case of =hoardy-web serve=, does that server instance allow archiving?
  Is it replay-only, maybe?

  If you fixed it and the error persists, press {{{button2(retryAllFailed,this button)}}}.

- =... Failed to archive <N> items because requests to the archiving server failed with: <STATUS> <REASON>: <RESPONSE>=:

  Your archiving sever is returning =HTTP= errors when =Hoardy-Web= is trying to archive data to it.
  See your archiving server's console for more information.

  Some common reasons it could be failing:
  - No space left on the device you are archiving to.
  - It's a bug, {{{reportit()}}}.

- One of
  - =... Failed to stash <N> items because <reason>= or
  - =... Failed to archive <N> items because <reason>=
  that are not the ones mentioned above:

  Stashing or archiving failed for some other reason.

  Some common reasons it could be failing:
  - No space left on the device your browser saves its local storage to.
  - It's a bug, {{{reportit()}}}.

- =Replay/Auto-replay is forbidden by the "Replay from the archiving server" option=:

  Enable {{{config2(replaySubmitHTTP,this option)}}}.

- =Replay/Auto-replay is impossible because the archiving server at `<URL>` <reason>=:

  Are you running [[../../tool/][=hoardy-web serve=]]?

  At the moment, that's the only archiving server that supports this feature.

  If you fixed it and the error persists, press {{{button2(retryAllFailed,this button)}}}.

- =Failed to open Hoardy-Web's database using `IndexedDB` API, but it appears that `IndexedDB` was previously used for stashing and/or archiving reqres. ...=:

  The most likely reason for this error is that you are running =Hoardy-Web= under a browser based on an older version of Firefox and you have recently enabled =Always use private browsing mode= setting in your browser's config.
  Older versions of Firefox forbid the use of =IndexedDB= API when that setting is set.

  To make archives currently saved in =IndexedDB= accessible to =Hoardy-Web= under =Always use private browsing mode= you need to:

  - Disable =Always use private browsing mode= browser setting and restart the browser, thus allowing =Hoardy-Web= access to =IndexedDB= again.
  - Disable {{{config2(preferIndexedDB,=Prefer 'IndexedDB' API= setting)}}}.
  - Disable all {{{div2(rearchive-methods,re-archival methods)}}}.
  - Enable {{{div2(rearchive.andRewrite,rewrites)}}},
  - press {{{button2(rearchiveAdjunctSaved,=Re-archive new= button)}}},
  - and wait for re-archival to finish.
  - Now, you can re-enable the =Always use private browsing mode= browser setting and restart you browser again.

  All old data should be available at the {{{button2(showSaved,=Saved in Local Storage= page)}}} now.

- =Bugged out: Failed to process <N> items because <reason>=:

  It's a bug, {{{reportit()}}}.

- Other error notifications should be completely self descriptive.
  If they are not, {{{reportit()}}}.
** Errors recorded in =reqres=, as seen in the logs
:PROPERTIES:
:CUSTOM_ID: reqres-errors
:END:

... at {{{logPage}}}.

Most error codes are produced by attaching one of the following prefixes to the raw error code given by the browser:

- =webRequest::= prefix is prepended to errors produced by the code working with =webRequest= API;

- =debugger::= prefix is prepended to errors produced by the code working with Chromium's Debugger API;

- =filterResponseData::= prefix is prepended to errors produced by =webRequest.filterResponseData= API (these can usually be ignored, since Firefox generates normal =webRequest::= codes for those reqres too, when it was an actual error; but =Hoardy-Web= still collects them, adhering to "collect everything as browser gives it, when possible" philosophy).

In particular, =webRequest::NS_= prefix on Firefox, and =webRequest::net::= and =debugger::net::= prefixes on Chromium signify various issues produced by the networking stacks of those browsers.
For instance:

  - =webRequest::NS_ERROR_ABORT= on Firefox and =webRequest::net::ERR_ABORTED= on Chromium signify that this request was aborted before it finished, e.g. because the originator tab was closed before it was fully loaded;
    Firefox also uses this code to mean what Chromium signifies with various =BLOCKED= codes;

  - =webRequest::net::ERR_BLOCKED_BY_CLIENT= on Chromium signifies that an extension blocked it;

  - =debugger::net::ERR_BLOCKED::= is a prefix for other errors when the request was blocked, e.g. by CSP;

  - =webRequest::NS_ERROR_NET= prefix on Firefox and =webRequest::net::ERR_FAILED= error on Chromium signify various networking issues.

The exception to the above rule of keeping everything as raw as possible are =webRequest::capture::= and =debugger::capture::= prefixes which signify various errors produced by =Hoardy-Web= itself in its =webRequest=- or =debugger=-handling code, respectively.
In particular:

- =webRequest::capture::EMIT_FORCED::BY_USER= and =debugger::capture::EMIT_FORCED::BY_USER= are produced when you forcefully advance a reqres from in-flight state by pressing {{{button2(stopAllInFlight,that)}}} or {{{button2(stopAllTabInFlight,this)}}} button;

- =debugger::capture::EMIT_FORCED::BY_DETACHED_DEBUGGER= is produced when Chromium debugger gets detached from its tab while a reqres inside that tab is still in flight;

- =debugger::capture::EMIT_FORCED::BY_CLOSED_TAB= is produced when a tab gets closed while a reqres inside of it is still in flight;

- =debugger::capture::NO_RESPONSE_BODY::= is a prefix for errors produced when getting request's response body from Chromium's debugger fails for various reasons;

- =webRequest::capture::CANCELED::NO_DEBUGGER= is produced when a non-main-frame request is canceled by =Hoardy-Web= because no debugger is available to capture it;
  in the case of a main frame request, =Hoardy-Web= will cancel the request and reload the tab, [[#chromium-quirk-reload][as discussed there]], so this error will not be produced;
  but it can happen if a page tries to load a sub-frame (like =iframe=) while the debugger for the tab (and, thus, the main frame) did not attach yet (which only happens for pages where Chromium disallows debugging, or when =Hoardy-Web= gets enabled after the page in question already started loading, e.g. the very first page after the browser starts);
  also, this can happen when the debugger gets detached after the main frame was captured but its resources are still loading.

- =webRequest::capture::CANCELED::BY_WORK_OFFLINE= is produced when the reqres was canceled as a result of one of the work offline toggles {{{perSource(workOffline)}}} being set.
* Quirks and Bugs
:PROPERTIES:
:CUSTOM_ID: bugs
:END:
#+BEGIN_EXPORT html
<div class="less">
#+END_EXPORT
If you are reading this page outside of the extension's UI be sure to read the [[#top][very top of this page]] first.
#+BEGIN_EXPORT html
</div>
#+END_EXPORT
** Known =Hoardy-Web='s own issues
- =Hoardy-Web= does not implement collection of WebSockets data on any of the supported browsers.

  (Firefox does not support it.
  Chromium does support it, in theory, but I have not tried using that API, so I have no idea how well it works.)

  This is low-priority issue since you can simply {{{button2(snapshotTab,take a =DOM= snapshot)}}} instead of capturing and later replaying WebSocket messages to in-page =JavaScript=.
  Also, capturing and archiving a =DOM= snapshot will free you from needing to run any =JavaScript= at all when you decide to replay the archived page later, which is nice.

- On Chromium, response data of background requests and requests made by other extensions does not get collected, since there's no tab to attach a debugger to, and I have not figured out how to attach debugger to other things yet.

- On Firefox, fetches that spawn new downloads will be marked as =problematic= by default, since Firefox's implementation of =webRequest.filterResponseData= API does not provide their contents to the extension and I have not figured out how to distinguish them from other fetches yet.
** Known issues that are consequences of issues of all supported browsers
- When =Hoardy-Web= is reloaded without using the {{{div2(reloadSelf,=Reload= button)}}} or {{{config2(autoReloadOnUpdates,=Auto-reload on updates= option)}}}, e.g. when =Hoardy-Web= is reloaded by clicking the "Reload" button in browser's extension list, then all {{{div2(this-tab-config,per-tab settings)}}} of all tabs will be reset to the {{{div2(root-tab-options,values used by the newly spawned root tabs)}}}.

  This issue is not applicable in the case when the reload happens because the extension was updated, in that case the browser will notify =Hoardy-Web= about it and =Hoardy-Web= will handle it properly, see the help string of the {{{div2(reloadSelf,=Reload= button)}}} for more info.

  But in the case of =Reload= buttons, the browser does not ask the extension nicely, so all unsaved internal state will be lost.

- If an =HTTP= server supplies the same header multiple times --- which happens sometimes, most commonly with =Set-Cookie= headers --- then the archived response headers will usually become weird, with multiple headers squished into a single value, separated by newline symbols.

  This is just the way both Firefox (usually) and Chromium (always) supply those headers to extensions and =Hoardy-Web= does not try to undo it.

- @@html:<span id="unsafe-saveas">@@ Browsers do not report a fake-Download file failing to be written to disk via =saveAs= API as an error.
  This makes {{{config2(archiveExportAs,=Export dumps via 'saveAs'= archival)}}} and {{{config2(rearchiveExportAs,similar re-archival)}}} options technically unsafe.
  @@html:</span>@@
** Known issues that are consequences of issues of Firefox-based desktop browsers: Firefox, Tor Browser, LibreWolf, etc
:PROPERTIES:
:CUSTOM_ID: firefox-bugs
:END:

- @@html:<span id="firefox-bug-no-post">@@ On Firefox-based browsers, without the [[../../firefox/][patch]], the browser only supplies =formData= to =webRequest.onBeforeRequest= handlers, thus making impossible to recover the actual request body for a =POST= request.
  @@html:</span>@@

  =Hoardy-Web= will mark such requests as having a =partial request body= and try its best to recover the data from =formData= structure, but if a =POST= request was uploading files, they won't be recoverable from =formData= (in fact, it is not even possible to tell if there were any files attached there), and so your archived request data will be incomplete even after =Hoardy-Web= did its best.

  With the above patch applied, small =POST= requests will be archived completely and correctly.
  =POST= requests that upload large files and only those will be marked as having a =partial request body=.

- =If-Modified-Since= and =If-None-Match= headers never get archived, because the browser never supplies them to the extensions. Thus, you can get =304 Not Modified= reqres response to a seemingly normal =GET= request.

- Reqres of already cached media files (images, audio, video, except for SVG and favicons) will end in =incomplete_fc= state because =webRequest.filterResponseData= API does not provide response bodies for such requests.
  {{{config2(archiveIncompleteResponse,This toggle)}}} controls if such reqres should be =picked=.

  By default, =Hoardy-Web= will =drop= them.
  Usually this is not a problem since such media will be archived on first (non-cached) access.
  But if you want to force everything on the page to be archived, you can reload the page without the cache with =Control+F5=.

- Firefox fails to run =onstop= method for =webRequest.filterResponseData= filter for the very first =HTTP/2= request the browser makes after you start it, thus making the reqres of that request =incomplete=.
  If {{{config2(workaroundFirefoxFirstRequest,this option)}}} is enabled, =Hoardy-Web= will transparently work around this bug by redirecting the very first navigation request to =about:blank= and then reloading the tab with its original URL.

- Firefox-based browsers provide no API for archiving WebSockets data at the moment, unfortunately.

- @@html:<span id="firefox-bug-race">@@ Firefox fails to provide response metadata when a request gets fulfilled by a service or shared worker after Firefox had already sent it to the server.
  @@html:</span>@@

  Firefox interrupts the networking code and generates =NS_ERROR_NET_ON_*= error about the event, but it fails to supply the response metadata generated by the service/shared worker in that event.

  =Hoardy-Web= then has to take guesses, and marks such reqres with =buggy response metadata= flag.
** Known issues that are consequences of issues of Firefox-based mobile browsers: Fenix aka Firefox for Android, Fennec, Mull, etc
:PROPERTIES:
:CUSTOM_ID: firefox-android-bugs
:END:

[[#firefox-bugs][All of the above]] apply, moreover:

- Archival {{{config2(archiveExportAs,by exporting using =saveAs=)}}} is not supported at the moment because of [[https://bugzilla.mozilla.org/show_bug.cgi?id=1914360][this bug]].
** Known issues that are consequences of issues of Chromium-based desktop browsers: Chromium, Chrome, etc
:PROPERTIES:
:CUSTOM_ID: chromium-bugs
:END:

On Chromium-based browsers, there is no way to get =HTTP= response data without attaching Chromium's debugger to a tab from which a request originates from.
This makes things a bit tricky, for instance:

- With {{{config2(collecting,this)}}} and {{{config2(workaroundChromiumResetRootTab,this option)}}} enabled, new tabs will be reset to {{{config2(workaroundChromiumResetRootTabURL,this value)}}} (=about:blank= by default) because the default of =chrome://newtab/= does not allow attaching debugger to the tabs with =chrome:= URLs.

- @@html:<span id="chromium-quirk-reload">@@ Requests made before the debugger is attached will get canceled by =Hoardy-Web=.
  So, for instance, when you middle-click a link, Chromium will open a new tab, but =Hoardy-Web= will block the requests from there until the debugger gets attached and then automatically reload the tab after.
  As side-effect of this, Chromium will show =Request blocked= page until the debugger is attached and the page is reloaded, meaning it will get visually stuck on =Request blocked= page if fetching the request ended up spawning a download instead of showing a page.
  The download will proceed as normal, though.
  @@html:</span>@@

- @@html:<span id="chromium-bug-detach">@@ You will get an annoying notification bar constantly displayed in the browser while {{{config2(collecting,=Hoardy-Web= is enabled)}}}.
  Closing that notification will detach the debugger.
  =Hoardy-Web= will reattach it immediately because it assumes you don't want to lose data and closing that notification on accident is, unfortunately, quite easy.
  @@html:</span>@@

  *However, closing the notification will make all in-flight requests lose their response data.*

  All alternatives to =Hoardy-Web= that work with Chromium suffer from the same issue.

  If you disable {{{config2(collecting,this option)}}} the debuggers will get detached only after all requests finish.
  But even if there are no requests in-flight the notification will not disappear immediately.
  Chromium takes its time updating the UI after the debugger is detached.

Moreover, Chromium has the following long-standing issues/bugs making things difficult:

- @@html:<span id="chromium-bug-no-large-files">@@ Chromium will automatically detach its debugger from a tab if it tries to save too much data into its debugger state.
  Which means that a tab that loads too much data too fast will get its debugger detached.
  Chromium does this to try and save memory, but this, among other issues, means that large images will fail to be properly archived, and any page that loads such files is likely to fail to be archived too.
  @@html:</span>@@

  This is a design limitation of Chromium debugging interface, there appears to be no work-around for this at the moment.

  Meanwhile, on Firefox, =Hoardy-Web= uses =webRequest.filterResponseData= API (not available on Chromium, because it greatly enhances browser's ad-blocking capabilities) which does not suffer from this problem.

- @@html:<span id="chromium-bug-autodetach">@@ Chromium will occasionally detach debuggers from some tabs at random.
  It just happens.
  Fortunately, =Hoardy-Web= will mark the resulting broken reqres as [[#problematic][problematic]] by default as they match the conditions of at least one of {{{config2(markProblematicNoResponse,this)}}}, {{{config2(markProblematicIncomplete,this)}}}, or {{{config2(markProblematicPickedWithErrors,that)}}} options.
  @@html:</span>@@

- @@html:<span id="chromium-bug-no-media">@@ Chromium handling of media files (audio and video) within its debugging interface is very strange.
  When Chromium encounters a media file, it immediately loads a first few frames of it, then cancels the rest of the download, generates a networking error debugging event, but forgets to give the already loaded data to it, and then, when the user clicks the play button, continues the download by requesting the rest of the file as normal.
  Thus, on Chromium, for media files =Hoardy-Web= will only ever get =206 Partial Content= =HTTP= responses with the first few kilobytes of file data missing.
  This bug has no good workaround, all alternatives to =Hoardy-Web= that work with Chromium work it around by silently re-downloading the file the second time in background.
  @@html:</span>@@

- @@html:<span id="chromium-bug-no-post">@@ Similarly to unpatched Firefox, Chromium-based browsers do not supply contents of files in =POST= request data.
  They do, however, provide a way to see if files were present in the request, so =Hoardy-Web= will mark such and only such requests as having a =partial request body=.
  There is no patch for Chromium to fix this, nor do I plan to make one (feel free to contribute one, though).
  @@html:</span>@@

- Chromium fails to provide =openerTabId= to tabs created with =chrome.tabs.create= API so in the unlikely case of opening two or more new tabs/windows in rapid succession via =Hoardy-Web= [[#context-menu][context menu actions]] and not giving them time to initialize =Hoardy-Web= could end up mixing up settings between the newly created tabs/windows.
  This bug is impossible to trigger unless your system is very slow or you are clicking things with automation tools like =AutoHotKey= or =xnee=.

- To properly collect all the data about a reqres, =Hoardy-Web= has to use both the data generated by =webRequest= API and Chromium's own debugging API events, using only one of those is usually insufficient.
  But Chromium generates different request IDs for events generated by these two different APIs and also generates those events in arbitrary order.
  Therefore, =Hoardy-Web= tracks reqres generated by both sets of APIs separately and then matches those two lists against each other heuristically, merging matching reqres together.
  Which is ugly enough.
  But then Chromium sometimes generates debugging API events and [[#chromium-bug-no-wre][forgets to produce the corresponding =webRequest= API events]], or vice versa, thus leaving some of those reqres unmatched.

  To work around that, =Hoardy-Web= waits {{{config2(workaroundChromiumDebugTimeout,this many seconds)}}} for new events to arrive, and if none do, forcefully finishes all unmatched but network-complete =in_flight= reqres.
  Yes, this means that some minor metadata fields (like =document_url=) of those reqres might be missing, but waiting more time usually won't fix it, so =Hoardy-Web= can't do anything else there.

- @@html:<span id="chromium-bug-stuck">@@ However, sometimes Chromium forgets to generate both =loading-complete= and =loading-failed= debugging events.
  This usually happens when a request gets started and then canceled by a page's =JavaScript=, or when you navigate between pages too fast.
  @@html:</span>@@

  In that case, =Hoardy-Web= can't tell if a reqres is just slow at being loaded or if Chromium forgot about it, so those reqres will get stuck in the =in_flight= state indefinitely, at least until their originator tab gets closed, or until you press one of {{{button2(stopAllInFlight,this)}}} or {{{button2(stopAllTabInFlight,that)}}} buttons.

  =Hoardy-Web= might get another workaround for this bug later.

- @@html:<span id="chromium-bug-no-wre">@@ Chromium sometimes simply does not generate any =webRequest= API events for a request it tracks.

  Most commonly, this happens for responses loaded from cache, but it can also happen for network fetches, apparently, at random.

  In this case, =Hoardy-Web= will collect no request data and metadata, this marking such reqres with both =partial request body= and =buggy request metadata= flags.
* Frequently Asked Questions
:PROPERTIES:
:CUSTOM_ID: faq
:END:
#+BEGIN_EXPORT html
<div class="less">
#+END_EXPORT
If you are reading this page outside of the extension's UI be sure to read the [[#top][very top of this page]] first.
#+BEGIN_EXPORT html
</div>
#+END_EXPORT
** Privacy and Security
*** Does =Hoardy-Web= send any of my captured web browsing data anywhere?
=Hoardy-Web= only ever sends your data to the {{{config2(submitHTTPURLBase,archiving =Server URL=)}}} you specify when the {{{config2(archiveSubmitHTTP,=Submit dumps via 'HTTP'= option)}}} is enabled.

Nowhere else.
Never else.
*** Does =Hoardy-Web= collect and send any telemetry anywhere?
For your convenience, =Hoardy-Web= saves some global stats across restarts (e.g., the {{{stat2(collected,Collected)}}}, {{{stat2(discarded,Discarded)}}}, {{{stat2(picked,Picked)}}}, and {{{stat2(dropped,Dropped)}}} lines).

However, none of those are ever sent anywhere and {{{button2(resetStats,you can reset them)}}} at any time.
*** Will the answers to the above two questions ever change in a future version of =Hoardy-Web=?
No.
I (the author) hate non-consensual data collection.

In fact, as you might have noticed, =Hoardy-Web=, unlike most other browser extensions, is almost trivial to reproducible-build from source on a POSIX-compliant system with a Nix package manager installed, and it has a [[https://oxij.org/software/hoardy-web/][privately operated source code mirror]].

This is by design, I expect a chunk of =Hoardy-Web= users to be paranoid enough to only ever build it from source and install the results manually into their LibreWolf or some such, leaving zero telemetry fingerprints anywhere.
*** =Hoardy-Web= asks for a lot of permissions, what does it use all those permissions for?

- =<all_urls>= permission is used so that =Hoardy-Web= could capture all URLs.
- =tabs= permission is used for tracking per-tab state and stats, making =Hoardy-Web='s toolbar icon show per-tab state, {{{button2(snapshotAll,taking =DOM= snapshot of all tabs)}}}, switching to reqres-related tabs from the logs {{{logPage}}}, etc.
- =webRequest=, =webRequestBlocking=, and (on Chromium) =debugger= permissions are used to track and capture =HTTP= requests and responses as well as to apply {{{div2(special-tab-options,=Tabs with special URLs= options)}}} and other URL-dependent settings when a tab navigates to a different URL.
- =webNavigation= permission is only used for internal logging at the moment.
- =storage= permission is used to save extension config and stats.
- =unlimitedStorage= permission is used for {{{div2(persistence-options,stashing and archival of captured data to browser's local storage)}}}.
- =menus= (=contextMenus= on Chromium) permission is used to add [[#context-menu][context menu actions]].
- =notifications= permission is used to {{{div2(notification-options,send notifications)}}}, which is mostly used for reporting various issues.
** Capture
*** Can I use =Hoardy-Web= to capture web pages while my browser runs with =JavaScript= disabled?
Yes.
*** Can I use =Hoardy-Web= to capture web pages that use a lot of =JavaScript=?
This is why {{{button2(snapshotTab,=DOM=)}}}-{{{button2(snapshotAll,snapshot)}}} buttons exist, see the following question.

In principle, =Hoardy-Web= will capture everything your browser fetches from the network as you browse the web, except for, at the moment, WebSockets data.
So, web pages using only simple UI-related =JavaScript= code will work fine when you start replaying them "from scratch" via [[../../tool/][=hoardy-web serve=, =hoardy-web mirror=]], or some such.

However, in the most general case, "from scratch" replay of pages dynamically generated via =JavaScript= is not guaranteed.
For example, consider a web page with a =JavaScript= code that generates a random number, then queries a remote server with that number, and then renders the result somehow.
Obviously, such a web page can not be replayed "from scratch" since it will generate a new random number and your archive probably won't have the corresponding server's response for it.
*** Can I use =Hoardy-Web= to capture a web page as it currently is, after all =JavaScript= was run, not as it was when it was last fetched from the network?
:PROPERTIES:
:CUSTOM_ID: faq-snapshot
:END:

Yes, you can capture =DOM= (Document Object Model) snapshots of all frames of the currently active tab by pressing {{{button2(snapshotTab,this button)}}} in the popup.

Doing that will generate and capture snapshots of raw =HTML='s or =XML='s for each frame contained in the currently active tab.
(Reqres-wise they will be =200 OK= responses, but with =protocol= set to =SNAPSHOT= and =method= set to =DOM=.)

You can also do that for all open tabs for which {{{tabconfig2(snapshottable,this setting)}}} is enabled all at once by pressing {{{button2(snapshotAll,that button)}}}.
*** How can I make =Hoardy-Web= capture a web page completely, especially when parts of it are loaded lazily?
:PROPERTIES:
:CUSTOM_ID: faq-lazy
:END:

In the most general case, you will have to scroll the page around and click random buttons and media elements.

=Hoardy-Web= has no "autopilot" for doing this, nor will it ever get one, at least as part of =Hoardy-Web= extension itself, since "autopiloting" is very website-specific.
So, at the moment, the most general semi-automated solution is to run a website-specific UserScript via [[https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/][Tampermonkey]] or some such, wait until everything finishes loading, and then take a {{{button2(snapshotTab,snapshot)}}}.
(=Hoardy-Web= will get an integration for automating that, eventually.)

On the other hand, if you

- run =Hoardy-Web= under Firefox,
- just want to load all lazily-loaded images the page already has (*not* load more stuff), and
- the page in question uses modern HTML5 lazy loading attributes instead of using =JavaScript= to do the same,

then you can simply go to =about:config= and toggle =dom.image-lazy-loading.enabled= to =false=.
All images will start being loaded eagerly after that.
*** Can I use =Hoardy-Web= to capture a web page without archiving it, look at it, decide if I want to save it, and archive it only if I do, all without reloading the page a second time?
:PROPERTIES:
:CUSTOM_ID: faq-limbo
:END:

Yes. This is why {{{tabconfig2(limbo,=Pick into limbo= setting)}}} exists.
See [[#limbo][above]] for more info.

In combination with {{{div2(closed-tab-options,=Closed tabs= options)}}} you can implement any of the following workflows:

- archive everything by default, but allow to exclude some things by manually discarding them from limbo;
- only archive things that are explicitly manually collected, discard everything else by default.
*** Why do pages under [[https://addons.mozilla.org/]] and [[https://chromewebstore.google.com/]] can not be captured by =Hoardy-Web=?
:PROPERTIES:
:CUSTOM_ID: store-pages
:END:

Browsers prevent extensions from running on extension store pages to prevent them from manipulating ratings, reviews, and similar things.
However, you can archive [[https://addons.mozilla.org/]] pages by running =Hoardy-Web= under Chromium and [[https://chromewebstore.google.com/]] pages by running =Hoardy-Web= under Firefox.
*** When running =Hoardy-Web= under Chromium, a lot of my captures fail with =debugger::capture::EMIT_FORCED::BY_DETACHED_DEBUGGER=, =debugger::capture::NO_RESPONSE_BODY::DETACHED_DEBUGGER=, =webRequest::capture::CANCELED::NO_DEBUGGER=, and similar errors. What do I do?
:PROPERTIES:
:CUSTOM_ID: faq-debugger
:END:

You are either

- pressing the =Cancel= or =Close= (cross) buttons in the Chromium's popup-toolbar telling you about the debugger being enabled, and so Chromium detaches it, breaking everything ([[#chromium-bug-detach][see there]]);

- pressing =Space= or =Escape= keyboard keys when doing things in Chromium's UI, but nothing at that particular moment reacts to the key you pressed, except there is that popup-toolbar... and so Chromium decides it must mean you want to press =Cancel= button there ... and detaches the debugger, breaking everything ([[#chromium-bug-detach][again]]);

  yes, this is really annoying, and this is a common problem for me, since I usually page-down using =Space= and press =Escape= a lot (usually to cancel selection, but sometimes also as a long-time Vim user trauma);

  the only solution to this I know of is to just not touch the keyboard at all, at least while things are still loading;
  i.e. just click on stuff using the mouse/track-point/touch-pad/touchscreen/etc, wait for the =T= ("Tracking") to vanish from the extension's badge, and only then let your (grabby and impatient for exercise via [[#shortcuts][keyboard shortcuts]]) fingers to touch the keyboard;

  even then, Chromium will detach its debugger from time to time seemingly at random, but at least it will be rare enough that you won't need to reload much;

- trying to capture large images, any audio files, or any videos;

  [[#chromium-bug-no-large-files][as discussed there]], this has no workaround, run =Hoardy-Web= under Firefox instead.

Also, [[#chromium-bug-autodetach][Chromium will occasionally detach its debugger at random]], it just happens.
*** When running =Hoardy-Web= under Firefox, my captures get marked as =buggy= all the time. What do I do?
:PROPERTIES:
:CUSTOM_ID: faq-disable-sw
:END:

This happens because of a [[#firefox-bug-race][race condition between webpage's service/shared worker and browser's networking code]].

Usually, you can ignore these =buggy= reqres, since loading another related page is likely to fulfill the same URL.

However, if this happens a lot to you, or if it annoys you, you can go to =about:config=, toggle =dom.serviceWorkers.enabled= to =false=, and restart the browser.
Alternatively, you can use =NoScript= or some such extension to disable =JavaScript=, and thus the offending service/shared workers, on the page in question.
*** Why does a (specific) URL or some part of it fails to be properly captured by =Hoardy-Web=?
Did you read the notes on the [[#bugs][bugs of the browser you are using]]?

Most notably:

- both Firefox- and Chromium-based browsers in their default builds [[#firefox-bug-no-post][fail]] to [[#chromium-bug-no-post][properly]] supply =POST= request data to their extensions; for Firefox-based browsers there exists a [[#firefox-bug-no-post][patch]] that fixes it, mostly; Chromium users are out of luck at the moment;

- on a Chromium-based browser, because of limitations of the Chromium's debugging interface, [[#chromium-bug-no-media][it is impossible to properly capture media files (both audio and video)]] and [[#chromium-bug-no-large-files][large files in general]]; this issue has no good work-around and, AFAIK, all alternatives to =Hoardy-Web= running on Chromium-based browser suffer from it (and work around it by silently re-downloading said files the second time in background); try using =Hoardy-Web= under a Firefox-based browser instead.
** Archival
*** The documentation claims that all =Hoardy-Web= archival methods except for {{{config2(archiveSubmitHTTP,submission via =HTTP=)}}} are unsafe. Why?
:PROPERTIES:
:CUSTOM_ID: faq-unsafe
:END:

Archival {{{config2(archiveExportAs,by exporting using =saveAs=)}}} (generation of fake-Downloads) can fail and **lose a bit of your collected data at a time** if you press a wrong button in you browser's UI, misconfigure your browser a bit, or [[#unsafe-saveas][your disk gets out of space unexpectedly]].

Archival {{{config2(archiveSaveLS,to browser's local storage)}}} (which is what =Hoardy-Web= is doing by default) can **loose all your collected data at the same time** if you uninstall the extension by accident.

Meanwhile, archival {{{config2(archiveSubmitHTTP,by submission via =HTTP=)}}} has none of these problems:

- =Hoardy-Web= keeps each reqres in memory until the archiving server responds with =200 OK= for that reqres;
- the archiving server only responds with =200 OK= response to =Hoardy-Web= after the dump is written and =fsync=-ed to disk;
- the archiving server never deletes any of your archived data;

  by using an archiving server, you can only loose your archived data if you go to its directory and delete some of it yourself, or if your disk dies, or if your file system gets corrupted;

  all of these problems can be trivially solved by doing backups regularly.

Archival {{{config2(archiveSaveLS,to browser's local storage)}}} was added because it was very easy to implement after [[#stashing][stashing]] was added.
It is the default because it usually works fine, it properly reports errors, has the most consistent behaviour across all browsers, and does not require the user to install any Python code, which helps with on-boarding.

In the ideal world, browsers would provide a better =saveAs= API which would have a less annoying UI for the user and would return out-of-disk-space errors to the extension, in which case {{{config2(archiveExportAs,exporting via =saveAs=)}}} would be the default.

As it is now, the only way to be absolutely sure you data is properly forever-saved to disk when the extension reports it archived is to use {{{config2(archiveSubmitHTTP,submission via =HTTP=)}}} or [[#re-archival][re-archive]] carefully.
*** When running =Hoardy-Web= under Firefox, enabling {{{config2(archiveExportAs,export via =saveAs=)}}} makes the browser's UI quite annoying. Can it be fixed?
:PROPERTIES:
:CUSTOM_ID: faq-firefox-saveas
:END:

Yes, go to =about:config= and toggle =browser.download.alwaysOpenPanel= to =false=.
** This page does not answer my question. What do I do?
:PROPERTIES:
:CUSTOM_ID: more
:END:

Did you try searching for stuff with =Control+F= on this page?
This document contains quite a bit of information.

Is your question about the =Hoardy-Web= browser extension in truth?
- If it's about =hoardy-web serve= replay server, see [[../../tool/][there]].
- If it's about another parts of the =Hoardy-Web= project, see [[../../][there]].

If none of those pages mention your problem, {{{reportit()}}}.

Usually, the simplest way to search for things is to simply =git clone= the [[../../][whole thing]] and then search there with =grep= or more advanced tools.
This applies not only to this project, but in general.
