#!/bin/sh -e
# purpose: generate a plain text preview of a WRR file via `w3m`

wrrarms get -l -e "net_url" -e "nquery_url|unquote_plus" -- "$1" | sed '
1 s/^/# url: /
2 s/^/# normalized: /
'
echo
wrrarms run -- w3m -T text/html -dump "$1"
